import Phaser from "phaser";
import type { WorldState } from "../../core/model/WorldState.ts";
import type { Transition } from "../../core/model/Events.ts";
import { WorldEngine } from "../../core/engine/WorldEngine.ts";
import { type TerrainType, findOpenSeaHeading } from "../../core/systems/NavigationSystem.ts";
import { WorldRenderer } from "../render/WorldRenderer.ts";
import { CameraController } from "../render/CameraController.ts";
// MinimapRenderer removed — map available in SPACE menu
import { CloudRenderer } from "../render/CloudRenderer.ts";
import { SeagullRenderer } from "../render/SeagullRenderer.ts";
import type { UIOverlayScene } from "./UIOverlayScene.ts";
import { FxManager } from "../render/FxManager.ts";
import { generateFlagTextures, generateCrewTexture } from "../render/TextureFactory.ts";
import { PortMarkerRenderer } from "../render/PortMarkerRenderer.ts";
import { WaterRenderer } from "../render/WaterRenderer.ts";
import { CartographicGrid } from "../render/CartographicGrid.ts";
import { CirrusRenderer } from "../render/CirrusRenderer.ts";

import { PalmRenderer } from "../render/PalmRenderer.ts";
import { InputMapper } from "../input/InputMapper.ts";
import { CommandQueue } from "../input/CommandQueue.ts";
import { PORTS } from "../../core/data/ports.ts";
import type { PortDef } from "../../core/data/ports.ts";
import { LANDMASSES, setLandmasses } from "../../core/data/geography.ts";
import type { LandmassDef, LandmassBbox } from "../../core/data/geography.ts";
import { vec2Dist, pointInLandmass, chaikinSmooth } from "../../core/services/Geometry.ts";
import { buildPortWaterCache } from "../../core/systems/PortWaterPositions.ts";
import { formatCalendarDate } from "../../core/systems/TimeSystem.ts";
import { t } from "../../core/i18n/index.ts";
import { txt } from "../ui/textStyle.ts";
// APP_VERSION moved to UIOverlayScene

const TICK_RATE = 20;
const TICK_MS = 1000 / TICK_RATE;

export class MainMapScene extends Phaser.Scene {
  private worldState!: WorldState;
  private engine!: WorldEngine;
  private worldRenderer!: WorldRenderer;
  private cameraCtrl!: CameraController;
  // minimap removed — info available in SPACE menu
  private cloudRenderer!: CloudRenderer;
  private cirrusRenderer!: CirrusRenderer;


  private palmRenderer!: PalmRenderer;
  private seaTextureTile: Phaser.GameObjects.TileSprite | null = null;
  private seagullRenderer!: SeagullRenderer;
  private uiOverlay!: UIOverlayScene;
  private waterRenderer!: WaterRenderer;
  private cartographicGrid!: CartographicGrid;
  private landGrid!: boolean[][];
  private inputMapper!: InputMapper;
  private commandQueue!: CommandQueue;

  private tickAccumulator = 0;
  /** Force furled sails on first update tick */
  private needSailReset = true;
  private sailResetFrames = 0;

  // dateText moved to UIOverlayScene
  private portPromptText: Phaser.GameObjects.Text | null = null;
  private portDialogOpen = false;
  private wasNearPort = false;
  // versionText moved to UIOverlayScene
  private onResize: ((gameSize: Phaser.Structs.Size) => void) | null = null;
  private windSound: Phaser.Sound.BaseSound | null = null;
  private gridContainer: Phaser.GameObjects.Container | null = null;
  private osmCities: Array<{ name: string; x: number; y: number }> = [];
  /** Cached nudged port positions (on land). Key = port id string. */
  private portSafePositions: Map<string, { x: number; y: number }> = new Map();
  /** All city/port labels with anchor points for zoom-independent positioning. */
  private cityLabels: Array<{ text: Phaser.GameObjects.Text; anchorX: number; anchorY: number; offsetPx: number }> = [];
  private cityGraphics: Phaser.GameObjects.Graphics | null = null;
  private flagImages: Phaser.GameObjects.Image[] = [];
  private coordLabels: Array<{ text: Phaser.GameObjects.Text; anchorX: number; anchorY: number }> = [];

  constructor() {
    super({ key: "MainMapScene" });
  }

  init(data?: { worldState?: WorldState }): void {
    if (data?.worldState) {
      this.worldState = data.worldState;
    }
  }

  create(): void {
    if (!this.worldState) {
      this.worldState = this.registry.get("worldState") as WorldState;
    }

    // Load real geography from JSON (generated by scripts/generate_caribbean_geo.mjs)
    this.initGeoData();

    this.createTilemap();
    generateFlagTextures(this);
    generateCrewTexture(this);

    const terrainQuery = this.createTerrainQuery();
    this.engine = new WorldEngine(terrainQuery);
    this.worldRenderer = new WorldRenderer();

    const mapW = 3200;
    const mapH = 2400;

    this.cameraCtrl = new CameraController(this.cameras.main);
    this.cameraCtrl.setBounds(0, 0, mapW, mapH);

    // Snap camera to player immediately so we don't start at (0,0)
    const playerEntity = this.worldState.entities[this.worldState.player.shipId as string];
    if (playerEntity) {
      this.cameraCtrl.snapTo(playerEntity.pos);
    }

    this.cloudRenderer = new CloudRenderer(this, mapW, mapH);
    this.cirrusRenderer = new CirrusRenderer(this, mapW, mapH);


    this.palmRenderer = new PalmRenderer(this, this.landGrid);
    this.seagullRenderer = new SeagullRenderer(this, this.landGrid);
    // Launch UI overlay scene (separate layer, no zoom)
    if (!this.scene.isActive("UIOverlayScene")) {
      this.scene.launch("UIOverlayScene");
    }
    this.uiOverlay = this.scene.get("UIOverlayScene") as UIOverlayScene;

    new FxManager(this);

    this.commandQueue = new CommandQueue();
    this.inputMapper = new InputMapper(this, this.commandQueue);
    // Ensure InputMapper starts with furled sails (synced with entity state)
    this.inputMapper.setSailLevel(0);

    // Date display moved to UIOverlayScene

    this.portPromptText = this.add.text(
      this.cameras.main.width / 2,
      this.cameras.main.height - 60,
      "",
      { ...txt(16, { color: "#ffdd44" }), backgroundColor: "#00000088", padding: { x: 12, y: 6 } },
    );
    this.portPromptText.setOrigin(0.5);
    this.portPromptText.setScrollFactor(0);
    this.portPromptText.setDepth(9500);
    this.portPromptText.setVisible(false);

    this.portDialogOpen = false;
    this.wasNearPort = false;

    // Version label moved to UIOverlayScene

    // Wind ambient sound
    if (this.cache.audio.exists("wind_loop")) {
      this.windSound = this.sound.add("wind_loop", { loop: true, volume: 0 });
      (this.windSound as Phaser.Sound.WebAudioSound).play();
    }

    if (this.input.keyboard) {
      this.input.keyboard.on("keydown-E", () => {
        const pe = this.worldState.entities[this.worldState.player.shipId as string];
        // E key: embark on ship when landed near anchor
        if (pe?.mode === "landed" && pe.anchorPos) {
          const distToShip = vec2Dist(pe.pos, pe.anchorPos);
          if (distToShip < 50) {
            this.commandQueue.push({ type: "Embark" });
            return;
          }
        }
        // E key: interact with port
        if (!this.portDialogOpen) {
          const nearPort = this.findNearPort();
          if (nearPort) {
            this.openPortDialog(nearPort);
          }
        }
      });

      this.input.keyboard.on("keydown-G", () => {
        this.toggleGrid();
      });

      this.input.keyboard.on("keydown-V", () => {
        this.worldRenderer.fogOfWarEnabled = !this.worldRenderer.fogOfWarEnabled;
        // minimap removed
        const mode = this.worldRenderer.fogOfWarEnabled ? "ON" : "OFF (test)";
        this.worldRenderer.applyEvents(this, [{ type: "Toast", message: `Fog of war: ${mode}` }]);
      });

      this.input.keyboard.on("keydown-L", () => {
        this.toggleLandMode();
      });

      this.input.keyboard.on("keydown-SPACE", () => {
        this.scene.launch("OptionsMenuScene", {
          worldState: this.worldState,
        });
        this.time.delayedCall(0, () => {
          this.scene.pause();
        });
      });
    }

    // Mouse wheel zoom
    this.input.on("wheel", (_pointer: Phaser.Input.Pointer, _over: Phaser.GameObjects.GameObject[], _dx: number, deltaY: number) => {
      this.cameraCtrl.adjustZoom(deltaY);
    });

    // Listen for PortApproachScene closing — resume ourselves and push ship to open sea
    this.events.on("resume", () => {
      this.portDialogOpen = false;
      this.pushShipToOpenSea();
      // Reset sails to minimum on departure
      this.inputMapper.setSailLevel(0.15);
    });

    // Dynamic resize handling
    this.onResize = (gameSize: Phaser.Structs.Size) => {
      this.cameras.main.setSize(gameSize.width, gameSize.height);
      // Reposition fixed HUD elements
      this.portPromptText!.setPosition(gameSize.width / 2, gameSize.height - 60);
      // versionText in UIOverlayScene
      // UI overlay repositions itself via its own resize handler
      // Minimap repositions itself each frame via cam.width
    };
    this.scale.on("resize", this.onResize);

    const portMarkers = new PortMarkerRenderer(this, this.landGrid).render();
    this.portSafePositions = portMarkers.portSafePositions;
    this.cityLabels = portMarkers.cityLabels;
    this.coordLabels = portMarkers.coordLabels;
    this.cityGraphics = portMarkers.cityGraphics;
    this.flagImages = portMarkers.flagImages;
    // OSM geographic labels removed — only port names shown
    this.worldRenderer.sync(this, this.worldState);
  }

  private initGeoData(): void {
    if (!this.cache.json.exists("caribbean_geo")) {
      console.warn("caribbean_geo.json not loaded — using fallback polygons");
      return;
    }

    const raw = this.cache.json.get("caribbean_geo") as {
      landmasses: Array<{
        id: string;
        polygon: number[][];
        bbox: [number, number, number, number];
      }>;
      osmCities: Array<{ name: string; x: number; y: number }>;
    };

    const parsed: LandmassDef[] = raw.landmasses.map((lm) => ({
      id: lm.id,
      polygon: lm.polygon.map(([x, y]) => ({ x, y })),
      bbox: {
        minX: lm.bbox[0],
        minY: lm.bbox[1],
        maxX: lm.bbox[2],
        maxY: lm.bbox[3],
      } as LandmassBbox,
    }));

    setLandmasses(parsed);
    buildPortWaterCache(); // Pre-compute water positions near ports for NPC navigation
    this.osmCities = raw.osmCities ?? [];
    console.log(`Loaded ${parsed.length} landmasses, ${this.osmCities.length} OSM cities`);
  }

  private createTilemap(): void {
    // All packs use OSM procedural rendering for now
    const mapW = 3200;
    const mapH = 2400;

    // Animated water surface with subtle wave patterns
    this.waterRenderer = new WaterRenderer(this, mapW, mapH);

    // Sea photo texture — mirror-tiled for seamless joins, UNDER wave layers
    if (this.textures.exists("sea_texture")) {
      // Scale source to 1024×1024 square, then mirror-tile → 2048×2048 seamless
      const srcImg = this.textures.get("sea_texture").getSourceImage() as HTMLImageElement;
      const HALF = 1024;
      const cropCanvas = document.createElement("canvas");
      cropCanvas.width = HALF;
      cropCanvas.height = HALF;
      const cctx = cropCanvas.getContext("2d")!;
      // Scale full source into 1024×1024 (slight stretch OK — it's water)
      cctx.drawImage(srcImg, 0, 0, srcImg.width, srcImg.height, 0, 0, HALF, HALF);

      // Mirror-tile: 2×2 → seamless 2048×2048
      const mirrorCanvas = document.createElement("canvas");
      mirrorCanvas.width = HALF * 2;
      mirrorCanvas.height = HALF * 2;
      const mctx = mirrorCanvas.getContext("2d")!;
      // Top-left: original
      mctx.drawImage(cropCanvas, 0, 0);
      // Top-right: flip horizontal
      mctx.save(); mctx.translate(HALF * 2, 0); mctx.scale(-1, 1);
      mctx.drawImage(cropCanvas, 0, 0); mctx.restore();
      // Bottom-left: flip vertical
      mctx.save(); mctx.translate(0, HALF * 2); mctx.scale(1, -1);
      mctx.drawImage(cropCanvas, 0, 0); mctx.restore();
      // Bottom-right: flip both
      mctx.save(); mctx.translate(HALF * 2, HALF * 2); mctx.scale(-1, -1);
      mctx.drawImage(cropCanvas, 0, 0); mctx.restore();

      const seaKey = "__sea_mirror";
      if (this.textures.exists(seaKey)) this.textures.remove(seaKey);
      const seaTex = this.textures.addCanvas(seaKey, mirrorCanvas);
      if (seaTex) seaTex.setFilter(Phaser.Textures.FilterMode.LINEAR);

      // TileSprite: scaled so 1 texture pixel ≈ 1 screen pixel at max zoom (12x)
      this.seaTextureTile = this.add.tileSprite(mapW / 2, mapH / 2, mapW, mapH, seaKey);
      this.seaTextureTile.setOrigin(0.5, 0.5);
      this.seaTextureTile.setDepth(-999);
      this.seaTextureTile.setAlpha(0.66);
      const MAX_ZOOM = 12;
      this.seaTextureTile.setTileScale(1 / MAX_ZOOM, 1 / MAX_ZOOM);
    }

    // Cartographic lat/lon grid (visible at far zoom only)
    this.cartographicGrid = new CartographicGrid(this, mapW, mapH);
    // No Graphics needed — eliminates potential WebGL bounding box artifacts

    // Shore gradient: full-size canvas + shadowBlur for smooth Gaussian glow
    const shoreCanvas = document.createElement("canvas");
    shoreCanvas.width = mapW;
    shoreCanvas.height = mapH;
    const sctx = shoreCanvas.getContext("2d")!;

    const fillCanvasPoly = (ctx: CanvasRenderingContext2D, pts: { x: number; y: number }[]) => {
      ctx.beginPath();
      ctx.moveTo(pts[0].x, pts[0].y);
      for (let i = 1; i < pts.length; i++) ctx.lineTo(pts[i].x, pts[i].y);
      ctx.closePath();
      ctx.fill();
    };

    // Pass 1: outer glow — turquoise shadow (strong, wide)
    sctx.shadowOffsetX = 0;
    sctx.shadowOffsetY = 0;
    sctx.shadowBlur = 25;
    sctx.shadowColor = "rgba(50, 180, 200, 0.7)";
    sctx.fillStyle = "rgba(50, 180, 200, 0.35)";
    for (const lm of LANDMASSES) {
      if (lm.polygon.length < 3) continue;
      fillCanvasPoly(sctx, chaikinSmooth(lm.polygon, 2));
    }

    // Pass 2: inner foam — bright white, tight
    sctx.shadowBlur = 10;
    sctx.shadowColor = "rgba(220, 245, 255, 0.6)";
    sctx.fillStyle = "rgba(220, 245, 255, 0.3)";
    for (const lm of LANDMASSES) {
      if (lm.polygon.length < 3) continue;
      fillCanvasPoly(sctx, chaikinSmooth(lm.polygon, 2));
    }

    const shoreKey = "__shore_shadow";
    if (this.textures.exists(shoreKey)) this.textures.remove(shoreKey);
    this.textures.addCanvas(shoreKey, shoreCanvas);
    const shoreImg = this.add.image(mapW / 2, mapH / 2, shoreKey);
    shoreImg.setDisplaySize(mapW, mapH);
    shoreImg.setOrigin(0.5, 0.5);
    shoreImg.setDepth(-950);

    const drawPoly = (gfx: Phaser.GameObjects.Graphics, pts: { x: number; y: number }[]) => {
      gfx.beginPath();
      gfx.moveTo(pts[0].x, pts[0].y);
      for (let i = 1; i < pts.length; i++) gfx.lineTo(pts[i].x, pts[i].y);
      gfx.closePath();
    };

    // Draw landmasses with smoothed coastlines
    const landGfx = this.add.graphics();
    landGfx.setDepth(-900);
    for (const lm of LANDMASSES) {
      if (lm.polygon.length < 3) continue;
      const smooth = chaikinSmooth(lm.polygon, 2);
      // Filled green land
      landGfx.fillStyle(0x5C6628, 1);
      drawPoly(landGfx, smooth);
      landGfx.fillPath();
    }

    // Beach: thick sand stroke on canvas + blur → gradient fade into land & sea
    const beachCanvas = document.createElement("canvas");
    beachCanvas.width = mapW;
    beachCanvas.height = mapH;
    const bchCtx = beachCanvas.getContext("2d")!;
    bchCtx.strokeStyle = "rgba(200, 168, 78, 0.9)";
    bchCtx.lineWidth = 6;
    bchCtx.lineJoin = "round";
    bchCtx.lineCap = "round";
    for (const lm of LANDMASSES) {
      if (lm.polygon.length < 3) continue;
      const smooth = chaikinSmooth(lm.polygon, 2);
      bchCtx.beginPath();
      bchCtx.moveTo(smooth[0].x, smooth[0].y);
      for (let i = 1; i < smooth.length; i++) bchCtx.lineTo(smooth[i].x, smooth[i].y);
      bchCtx.closePath();
      bchCtx.stroke();
    }
    // Blur for smooth gradient on both sides
    const beachBlurred = document.createElement("canvas");
    beachBlurred.width = mapW;
    beachBlurred.height = mapH;
    const bbCtx = beachBlurred.getContext("2d")!;
    bbCtx.filter = "blur(3px)";
    bbCtx.drawImage(beachCanvas, 0, 0);

    const beachKey = "__beach_blurred";
    if (this.textures.exists(beachKey)) this.textures.remove(beachKey);
    this.textures.addCanvas(beachKey, beachBlurred);
    const beachImg = this.add.image(mapW / 2, mapH / 2, beachKey);
    beachImg.setDisplaySize(mapW, mapH);
    beachImg.setOrigin(0.5, 0.5);
    beachImg.setDepth(-895); // above land texture (-899), below cities

    // Build land grid from polygons for navigation/seagulls
    // Sample a 4x4 sub-grid per cell so small islands (< 32px) aren't missed
    const CELL = 32;
    const cols = Math.ceil(mapW / CELL);
    const rows = Math.ceil(mapH / CELL);
    const SUB = 4; // sub-samples per axis
    const step = CELL / SUB;
    this.landGrid = Array.from({ length: rows }, () => Array(cols).fill(false));
    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) {
        let found = false;
        for (let sy = 0; sy < SUB && !found; sy++) {
          for (let sx = 0; sx < SUB && !found; sx++) {
            const px = c * CELL + step * (sx + 0.5);
            const py = r * CELL + step * (sy + 0.5);
            const pt = { x: px, y: py };
            for (const lm of LANDMASSES) {
              if (pointInLandmass(pt, lm)) {
                this.landGrid[r][c] = true;
                found = true;
                break;
              }
            }
          }
        }
      }
    }
  }

  private toggleLandMode(): void {
    const playerEntity = this.worldState.entities[this.worldState.player.shipId as string];
    if (!playerEntity) return;

    // L key only used to embark (return to ship) — disembark is automatic on land collision
    if (playerEntity.mode === "landed") {
      this.commandQueue.push({ type: "Embark" });
    }
  }

  private createTerrainQuery(): (wx: number, wy: number) => TerrainType {
    return (wx: number, wy: number): TerrainType => {
      if (wx < 0 || wy < 0 || wx > 3200 || wy > 2400) {
        return "land";
      }

      const pt = { x: wx, y: wy };
      for (const lm of LANDMASSES) {
        if (pointInLandmass(pt, lm)) {
          return "land";
        }
      }
      return "sea";
    };
  }

  /** Convert lon/lat to pixel coordinates (same Mercator formula as cities.ts geoToMap). */
  private geoToPixel(lon: number, lat: number): { x: number; y: number } {
    const mercYFn = (l: number) => Math.log(Math.tan(Math.PI / 4 + ((l * Math.PI) / 180) / 2));
    const yTop = mercYFn(35);
    const yBot = mercYFn(7);
    return {
      x: ((lon - (-100)) / 45) * 3200,
      y: ((yTop - mercYFn(lat)) / (yTop - yBot)) * 2400,
    };
  }

  private toggleGrid(): void {
    if (this.gridContainer) {
      this.gridContainer.destroy();
      this.gridContainer = null;
      return;
    }
    this.gridContainer = this.add.container(0, 0);
    this.gridContainer.setDepth(9000);

    const g = this.add.graphics();
    this.gridContainer.add(g);

    // Draw longitude lines (vertical) from 98°W to 56°W
    for (let lon = -98; lon <= -56; lon += 2) {
      const px = this.geoToPixel(lon, 0).x;
      const isMajor = (-lon) % 10 === 0;
      g.lineStyle(isMajor ? 1.5 : 0.5, 0xffffff, isMajor ? 0.5 : 0.2);
      g.lineBetween(px, 0, px, 2400);
      // Label
      const label = this.add.text(px, 4, `${-lon}°W`, {
        ...txt(isMajor ? 11 : 9, { color: "#ffffff" }),
        backgroundColor: "#00000088",
        padding: { x: 2, y: 1 },
      });
      label.setOrigin(0.5, 0);
      this.gridContainer.add(label);
    }

    // Draw latitude lines (horizontal) from 8°N to 34°N
    for (let lat = 8; lat <= 34; lat += 2) {
      const py = this.geoToPixel(0, lat).y;
      const isMajor = lat % 10 === 0;
      g.lineStyle(isMajor ? 1.5 : 0.5, 0xffffff, isMajor ? 0.5 : 0.2);
      g.lineBetween(0, py, 3200, py);
      // Label
      const label = this.add.text(4, py, `${lat}°N`, {
        ...txt(isMajor ? 11 : 9, { color: "#ffffff" }),
        backgroundColor: "#00000088",
        padding: { x: 2, y: 1 },
      });
      label.setOrigin(0, 0.5);
      this.gridContainer.add(label);
    }

    // Mark each port with its coordinate
    for (const [, port] of Object.entries(PORTS)) {
      const px = port.pos.x;
      const py = port.pos.y;
      // Reverse-calculate lon/lat from pixel position (Mercator inverse)
      const lon = (px / 3200) * 45 + (-100);
      // For lat, we need inverse Mercator — approximate with display
      const mercYFn = (l: number) => Math.log(Math.tan(Math.PI / 4 + ((l * Math.PI) / 180) / 2));
      const yTop = mercYFn(35);
      const yBot = mercYFn(7);
      const mercLat = yTop - (py / 2400) * (yTop - yBot);
      const lat = (2 * Math.atan(Math.exp(mercLat)) - Math.PI / 2) * 180 / Math.PI;
      const coordLabel = this.add.text(px, py + 14, `${(-lon).toFixed(1)}°W ${lat.toFixed(1)}°N`, {
        ...txt(8, { color: "#ffff00" }),
        backgroundColor: "#000000aa",
        padding: { x: 2, y: 1 },
      });
      coordLabel.setOrigin(0.5, 0);
      this.gridContainer.add(coordLabel);
    }
  }

  private findNearPort(): (typeof PORTS)[keyof typeof PORTS] | null {
    const playerEntity = this.worldState.entities[this.worldState.player.shipId as string];
    if (!playerEntity) return null;

    const isLanded = playerEntity.mode === "landed";
    const radius = isLanded ? 20 : 6;

    for (const [portKey, port] of Object.entries(PORTS)) {
      // Use coast-snapped position (on land, adjacent to water) for all checks
      const checkPos = this.portSafePositions.get(portKey) ?? port.pos;
      const dist = vec2Dist(playerEntity.pos, checkPos);
      if (dist <= radius) {
        return port;
      }
    }
    return null;
  }

  private openPortDialog(port: PortDef): void {
    this.portDialogOpen = true;
    const portKey = Object.entries(PORTS).find(([_, p]) => p === port)?.[0];
    if (!portKey) return;

    // Stop the ship when approaching a port from sea
    const playerEntity = this.worldState.entities[this.worldState.player.shipId as string];
    if (playerEntity && playerEntity.mode !== "landed") {
      const shipId = this.worldState.player.shipId as string;
      this.worldState = {
        ...this.worldState,
        entities: {
          ...this.worldState.entities,
          [shipId]: {
            ...playerEntity,
            vel: { x: 0, y: 0 },
            sailLevel: 0,
          },
        },
      };
      this.registry.set("worldState", this.worldState);
    }

    this.scene.launch("PortApproachScene", {
      worldState: this.worldState,
      portId: portKey,
    });
    this.time.delayedCall(0, () => {
      this.scene.pause();
    });
  }

  update(_time: number, delta: number): void {
    // Force furled sails: skip first 3 frames entirely to flush stale keyboard state
    if (this.needSailReset) {
      this.needSailReset = false;
      this.sailResetFrames = 3;
      const sid = this.worldState.player.shipId as string;
      const ship = this.worldState.entities[sid];
      if (ship) {
        this.worldState = {
          ...this.worldState,
          entities: {
            ...this.worldState.entities,
            [sid]: { ...ship, sailLevel: 0, vel: { x: 0, y: 0 } },
          },
        };
        this.registry.set("worldState", this.worldState);
      }
    }
    if (this.sailResetFrames > 0) {
      this.sailResetFrames--;
      // Drain any stale keyboard commands and discard them
      this.inputMapper.setSailLevel(0);
      this.commandQueue.drain();
      return; // Skip entire update — no input, no simulation, no movement
    }

    // Sync input mode with entity mode
    const pe = this.worldState.entities[this.worldState.player.shipId as string];
    this.inputMapper.setLandedMode(pe?.mode === "landed", pe?.sailLevel);
    this.inputMapper.update();

    // Mouse steering: hold left button to steer toward cursor
    this.updateMouseSteering(pe);

    // Game speed multiplier scales the effective simulation rate
    const speedMultiplier = this.worldState.gameSpeed ?? 1.2;
    this.tickAccumulator += delta * speedMultiplier;

    while (this.tickAccumulator >= TICK_MS) {
      this.tickAccumulator -= TICK_MS;

      const commands = this.commandQueue.drain();
      const result = this.engine.apply(this.worldState, commands, 1);
      this.worldState = result.state;
      this.registry.set("worldState", this.worldState);

      if (result.events.length > 0) {
        this.worldRenderer.applyEvents(this, result.events);
      }

      if (result.transitions) {
        for (const t of result.transitions) {
          this.handleTransition(t);
          return;
        }
      }
    }

    // Interpolation factor: how far between ticks we are (0→1)
    const interpAlpha = this.tickAccumulator / TICK_MS;

    // Sync fog-of-war from settings (debug mode disables it)
    const debugMode = localStorage.getItem("pc_debug") !== "0";
    const fogSetting = localStorage.getItem("pc_fog") === "1";
    this.worldRenderer.fogOfWarEnabled = debugMode ? false : fogSetting;

    this.worldRenderer.sync(this, this.worldState);

    const playerEntity = this.worldState.entities[this.worldState.player.shipId as string];
    if (playerEntity) {
      // Interpolate player position between ticks for smooth movement
      const vel = playerEntity.vel ?? { x: 0, y: 0 };
      const interpPos = {
        x: playerEntity.pos.x + vel.x * interpAlpha,
        y: playerEntity.pos.y + vel.y * interpAlpha,
      };
      this.cameraCtrl.setTarget(interpPos);
      this.cameraCtrl.update();
      this.worldRenderer.drawVisionCircle(this, playerEntity.pos);
    }

    // City zoom scaling
    const camZoom = this.cameras.main.zoom;

    // City ICONS (Graphics): fade out at far zoom, hidden below zoom 2
    if (this.cityGraphics) {
      const iconAlpha = camZoom < 2 ? 0 : camZoom < 3 ? (camZoom - 2) : 1;
      this.cityGraphics.setAlpha(iconAlpha);
      this.cityGraphics.setVisible(camZoom > 2);
    }

    // FLAGS: scale down, disappear later than icons
    for (const flag of this.flagImages) {
      const flagT = Math.min(1, (camZoom - 1.5) / (5 - 1.5));
      const flagScale = 0.15 + flagT * 0.35; // 0.15 → 0.5
      flag.setScale(flagScale);
      flag.setVisible(camZoom > 1.6);
    }

    // LABELS: sqrt scaling, grid labels hide with grid
    const labelScale = 1 / Math.sqrt(camZoom);
    const gridAlpha = camZoom < 2.2 ? 1 : camZoom < 3 ? 1 - (camZoom - 2.2) / 0.8 : 0;
    for (const entry of this.cityLabels) {
      const isGrid = entry.text.getData("isGrid");
      if (isGrid) {
        entry.text.setVisible(gridAlpha > 0.01);
        entry.text.setAlpha(gridAlpha);
      }
      entry.text.setScale(labelScale);
      entry.text.setPosition(
        entry.anchorX + entry.offsetPx / camZoom,
        entry.anchorY,
      );
    }

    // Coord labels hidden — backend only, not shown to player
    for (const entry of this.coordLabels) {
      entry.text.setVisible(false);
    }

    this.cloudRenderer.update(this.worldState.weather.windDirRad, this.worldState.weather.windStrength);
    this.cirrusRenderer.update(this.worldState.weather.windDirRad, this.worldState.weather.windStrength);


    this.palmRenderer.update();

    // Sea texture: smooth alpha ramp from zoom 2 to max zoom
    if (this.seaTextureTile) {
      const z = this.cameras.main.zoom;
      // zoom <2: invisible, zoom 2→12: linear 0→0.50
      const t = Math.max(0, Math.min(1, (z - 2) / (12 - 2)));
      this.seaTextureTile.setAlpha(t * 0.50);
    }

    this.seagullRenderer.update(this.worldState.weather.windDirRad, this.worldState.weather.windStrength);
    this.uiOverlay?.updateWind(this.worldState.weather.windDirRad, this.worldState.weather.windStrength);

    // Animate water surface with wind
    this.waterRenderer.update(this.worldState.weather.windDirRad, this.worldState.weather.windStrength);
    // Cartographic grid: show/hide based on zoom
    this.cartographicGrid.update();

    // Wind sound volume follows wind strength
    if (this.windSound && "setVolume" in this.windSound) {
      (this.windSound as Phaser.Sound.WebAudioSound).setVolume(
        this.worldState.weather.windStrength * 0.6,
      );
    }

    // Auto-embark: when crew walks very close to the anchored ship, board automatically
    if (playerEntity?.mode === "landed" && playerEntity.anchorPos) {
      const distToShip = vec2Dist(playerEntity.pos, playerEntity.anchorPos);
      if (distToShip < 20) {
        this.commandQueue.push({ type: "Embark" });
      }
    }

    this.updateHud();
    this.updatePortPrompt();
  }

  /** Steer ship/crew toward mouse cursor while left button is held. */
  private updateMouseSteering(playerEntity: { pos: { x: number; y: number }; heading: number; mode: string; sailLevel: number } | undefined): void {
    if (!playerEntity) return;
    // LPM does nothing while sailing — only works on land
    if (playerEntity.mode !== "landed") return;
    const pointer = this.input.activePointer;
    if (!pointer.isDown || pointer.button !== 0) return;

    // Convert screen coordinates to world coordinates
    const cam = this.cameras.main;
    const worldX = pointer.x / cam.zoom + cam.scrollX;
    const worldY = pointer.y / cam.zoom + cam.scrollY;

    const dx = worldX - playerEntity.pos.x;
    const dy = worldY - playerEntity.pos.y;
    const dist = Math.sqrt(dx * dx + dy * dy);
    if (dist < 5) return; // too close, ignore

    // heading: 0=N, PI/2=E, PI=S — atan2(dx, -dy) matches this convention
    const targetHeading = Math.atan2(dx, -dy);

    if (playerEntity.mode === "landed") {
      // Land mode: set heading and walk
      this.commandQueue.push({ type: "SetHeading", heading: targetHeading });
      this.commandQueue.push({ type: "SetSailLevel", value: 1 });
    } else {
      // Sailing mode: steer only, do NOT change sails
      this.commandQueue.push({ type: "SetHeading", heading: targetHeading });
    }
  }

  private updateHud(): void {
    // Date in UIOverlayScene (no time, just date)
    const dateStr = formatCalendarDate(this.worldState.time, this.worldState.startYear);
    const uiOverlay = this.scene.get("UIOverlayScene") as import("./UIOverlayScene.ts").UIOverlayScene;
    if (uiOverlay?.updateDate) {
      uiOverlay.updateDate(dateStr);
    }
  }

  /** After leaving port dialog, push ship perpendicular to coast toward open sea. */
  private pushShipToOpenSea(): void {
    const shipId = this.worldState.player.shipId as string;
    const entity = this.worldState.entities[shipId];
    if (!entity || entity.mode !== "sailing") return;

    const terrainQuery = (x: number, y: number): TerrainType => {
      const col = Math.floor(x / 32);
      const row = Math.floor(y / 32);
      if (row < 0 || row >= this.landGrid.length || col < 0 || col >= (this.landGrid[0]?.length ?? 0)) {
        return "sea";
      }
      return this.landGrid[row][col] ? "land" : "sea";
    };

    const seaHeading = findOpenSeaHeading(entity.pos.x, entity.pos.y, terrainQuery, entity.heading);
    const pushDist = 15;
    this.worldState = {
      ...this.worldState,
      entities: {
        ...this.worldState.entities,
        [shipId]: {
          ...entity,
          heading: seaHeading,
          sailLevel: 0.15, // minimal sails on departure
          pos: {
            x: entity.pos.x + Math.sin(seaHeading) * pushDist,
            y: entity.pos.y - Math.cos(seaHeading) * pushDist,
          },
          embarkTick: this.worldState.time.tick,
        },
      },
    };
  }

  private updatePortPrompt(): void {
    const playerEntity = this.worldState.entities[this.worldState.player.shipId as string];

    // Check for nearby port — works in BOTH sailing and landed modes
    const nearPort = this.findNearPort();
    if (nearPort) {
      if (!this.wasNearPort && !this.portDialogOpen) {
        this.openPortDialog(nearPort);
      }
      this.wasNearPort = true;
      const promptPortKey = Object.entries(PORTS).find(([_, p]) => p === nearPort)?.[0] ?? "";
      this.portPromptText!.setText(t("approach.prompt", { name: t("port." + promptPortKey + ".name") }));
      this.portPromptText!.setVisible(!this.portDialogOpen);
      return;
    }

    this.wasNearPort = false;

    // Landed mode: show ship boarding prompt when near anchor
    if (playerEntity?.mode === "landed" && playerEntity.anchorPos) {
      const distToShip = vec2Dist(playerEntity.pos, playerEntity.anchorPos);
      if (distToShip < 50) {
        this.portPromptText!.setText(t("hud.embark_ship_prompt"));
        this.portPromptText!.setVisible(true);
        return;
      }
      // Far from ship: show general embark hint
      this.portPromptText!.setText(t("hud.embark_prompt"));
      this.portPromptText!.setVisible(true);
      return;
    }

    this.portPromptText!.setVisible(false);
  }

  private handleTransition(t: Transition): void {
    const payload = t.payload as Record<string, unknown> | undefined;
    switch (t.scene) {
      case "Port":
        this.scene.start("PortScene", { worldState: this.worldState, portId: payload?.portId });
        break;
      case "SeaBattle":
        this.scene.start("SeaBattleScene", { worldState: this.worldState, enemyId: payload?.enemyId });
        break;
      default:
        break;
    }
  }

  shutdown(): void {
    if (this.onResize) {
      this.scale.off("resize", this.onResize);
      this.onResize = null;
    }
    this.worldRenderer.destroy();
    this.cartographicGrid.destroy();
    this.cloudRenderer.destroy();
    this.cirrusRenderer.destroy();


    this.palmRenderer.destroy();
    this.waterRenderer.destroy();
    this.seagullRenderer.destroy();
    this.scene.stop("UIOverlayScene");
    this.inputMapper.destroy();
    if (this.windSound) {
      this.windSound.stop();
      this.windSound.destroy();
      this.windSound = null;
    }
  }
}
