import Phaser from "phaser";
import type { WorldState } from "../../core/model/WorldState.ts";
import type { Transition } from "../../core/model/Events.ts";
import { WorldEngine } from "../../core/engine/WorldEngine.ts";
import type { TerrainType } from "../../core/systems/NavigationSystem.ts";
import { WorldRenderer } from "../render/WorldRenderer.ts";
import { CameraController } from "../render/CameraController.ts";
import { MinimapRenderer } from "../render/MinimapRenderer.ts";
import { CloudRenderer } from "../render/CloudRenderer.ts";
import { SeagullRenderer } from "../render/SeagullRenderer.ts";
import { WindCompassRenderer } from "../render/WindCompassRenderer.ts";
import { FxManager } from "../render/FxManager.ts";
import { InputMapper } from "../input/InputMapper.ts";
import { CommandQueue } from "../input/CommandQueue.ts";
import { PORTS } from "../../core/data/ports.ts";
import type { PortDef } from "../../core/data/ports.ts";
import { FACTIONS } from "../../core/data/factions.ts";
import { LANDMASSES, setLandmasses } from "../../core/data/geography.ts";
import type { LandmassDef, LandmassBbox } from "../../core/data/geography.ts";
import { vec2Dist, pointInLandmass } from "../../core/services/Geometry.ts";
import { formatCalendarDate } from "../../core/systems/TimeSystem.ts";
import { t } from "../../core/i18n/index.ts";
import { txt } from "../ui/textStyle.ts";
import { APP_VERSION } from "../../version.ts";

const TICK_RATE = 20;
const TICK_MS = 1000 / TICK_RATE;

export class MainMapScene extends Phaser.Scene {
  private worldState!: WorldState;
  private engine!: WorldEngine;
  private worldRenderer!: WorldRenderer;
  private cameraCtrl!: CameraController;
  private minimap!: MinimapRenderer;
  private cloudRenderer!: CloudRenderer;
  private seagullRenderer!: SeagullRenderer;
  private windCompass!: WindCompassRenderer;
  private waterTileSprite: Phaser.GameObjects.TileSprite | null = null;
  private landGrid!: boolean[][];
  private inputMapper!: InputMapper;
  private commandQueue!: CommandQueue;

  private tickAccumulator = 0;

  private dateText!: Phaser.GameObjects.Text;
  private hudText!: Phaser.GameObjects.Text;
  private portPromptText: Phaser.GameObjects.Text | null = null;
  private portDialogOpen = false;
  private wasNearPort = false;
  private versionText!: Phaser.GameObjects.Text;
  private onResize: ((gameSize: Phaser.Structs.Size) => void) | null = null;
  private windSound: Phaser.Sound.BaseSound | null = null;
  private gridContainer: Phaser.GameObjects.Container | null = null;
  private osmCities: Array<{ name: string; x: number; y: number }> = [];
  /** Cached nudged port positions (on land). Key = port id string. */
  private portSafePositions: Map<string, { x: number; y: number }> = new Map();

  constructor() {
    super({ key: "MainMapScene" });
  }

  init(data?: { worldState?: WorldState }): void {
    if (data?.worldState) {
      this.worldState = data.worldState;
    }
  }

  create(): void {
    if (!this.worldState) {
      this.worldState = this.registry.get("worldState") as WorldState;
    }

    // Load real geography from JSON (generated by scripts/generate_caribbean_geo.mjs)
    this.initGeoData();

    this.createTilemap();
    this.generateFlagTextures();
    this.generateCrewTexture();

    const terrainQuery = this.createTerrainQuery();
    this.engine = new WorldEngine(terrainQuery);
    this.worldRenderer = new WorldRenderer();

    const mapW = 3200;
    const mapH = 2400;

    this.cameraCtrl = new CameraController(this.cameras.main);
    this.cameraCtrl.setBounds(0, 0, mapW, mapH);

    // Snap camera to player immediately so we don't start at (0,0)
    const playerEntity = this.worldState.entities[this.worldState.player.shipId as string];
    if (playerEntity) {
      this.cameraCtrl.snapTo(playerEntity.pos);
    }

    this.minimap = new MinimapRenderer(this, mapW, mapH);
    this.cloudRenderer = new CloudRenderer(this, mapW, mapH);
    this.seagullRenderer = new SeagullRenderer(this, this.landGrid);
    this.windCompass = new WindCompassRenderer(this);

    new FxManager(this);

    this.commandQueue = new CommandQueue();
    this.inputMapper = new InputMapper(this, this.commandQueue);

    // Date display — small black text, top-left
    this.dateText = this.add.text(10, 8, "", txt(11, { color: "#111111" }));
    this.dateText.setScrollFactor(0);
    this.dateText.setDepth(9500);

    // Compact HUD — below date
    this.hudText = this.add.text(10, 40, "", {
      ...txt(11, { color: "#ffffff" }),
      backgroundColor: "#00000088",
      padding: { x: 6, y: 3 },
    });
    this.hudText.setScrollFactor(0);
    this.hudText.setDepth(9500);

    this.portPromptText = this.add.text(
      this.cameras.main.width / 2,
      this.cameras.main.height - 60,
      "",
      { ...txt(16, { color: "#ffdd44" }), backgroundColor: "#00000088", padding: { x: 12, y: 6 } },
    );
    this.portPromptText.setOrigin(0.5);
    this.portPromptText.setScrollFactor(0);
    this.portPromptText.setDepth(9500);
    this.portPromptText.setVisible(false);

    this.portDialogOpen = false;
    this.wasNearPort = false;

    // Version label — bottom-right
    this.versionText = this.add.text(
      this.cameras.main.width - 6, this.cameras.main.height - 4,
      `v${APP_VERSION}`, {
        ...txt(12, { color: "#aaaaaa" }),
        stroke: "#000000",
        strokeThickness: 2,
      },
    );
    this.versionText.setOrigin(1, 1);
    this.versionText.setScrollFactor(0);
    this.versionText.setDepth(9500);

    // Wind ambient sound
    if (this.cache.audio.exists("wind_loop")) {
      this.windSound = this.sound.add("wind_loop", { loop: true, volume: 0 });
      (this.windSound as Phaser.Sound.WebAudioSound).play();
    }

    if (this.input.keyboard) {
      this.input.keyboard.on("keydown-E", () => {
        const pe = this.worldState.entities[this.worldState.player.shipId as string];
        // E key: embark on ship when landed near anchor
        if (pe?.mode === "landed" && pe.anchorPos) {
          const distToShip = vec2Dist(pe.pos, pe.anchorPos);
          if (distToShip < 50) {
            this.commandQueue.push({ type: "Embark" });
            return;
          }
        }
        // E key: interact with port
        if (!this.portDialogOpen) {
          const nearPort = this.findNearPort();
          if (nearPort) {
            this.openPortDialog(nearPort);
          }
        }
      });

      this.input.keyboard.on("keydown-G", () => {
        this.toggleGrid();
      });

      this.input.keyboard.on("keydown-L", () => {
        this.toggleLandMode();
      });

      this.input.keyboard.on("keydown-SPACE", () => {
        this.scene.launch("OptionsMenuScene", {
          worldState: this.worldState,
        });
        this.time.delayedCall(0, () => {
          this.scene.pause();
        });
      });
    }

    // Mouse wheel zoom
    this.input.on("wheel", (_pointer: Phaser.Input.Pointer, _over: Phaser.GameObjects.GameObject[], _dx: number, deltaY: number) => {
      this.cameraCtrl.adjustZoom(deltaY);
    });

    // Listen for PortApproachScene closing — resume ourselves
    this.events.on("resume", () => {
      this.portDialogOpen = false;
    });

    // Dynamic resize handling
    this.onResize = (gameSize: Phaser.Structs.Size) => {
      this.cameras.main.setSize(gameSize.width, gameSize.height);
      // Reposition fixed HUD elements
      this.portPromptText!.setPosition(gameSize.width / 2, gameSize.height - 60);
      this.versionText.setPosition(gameSize.width - 6, gameSize.height - 4);
      this.windCompass.reposition(gameSize.width);
      // Minimap repositions itself each frame via cam.width
    };
    this.scale.on("resize", this.onResize);

    this.drawPortMarkers();
    this.drawOSMCityLabels();
    this.worldRenderer.sync(this, this.worldState);
  }

  private initGeoData(): void {
    if (!this.cache.json.exists("caribbean_geo")) {
      console.warn("caribbean_geo.json not loaded — using fallback polygons");
      return;
    }

    const raw = this.cache.json.get("caribbean_geo") as {
      landmasses: Array<{
        id: string;
        polygon: number[][];
        bbox: [number, number, number, number];
      }>;
      osmCities: Array<{ name: string; x: number; y: number }>;
    };

    const parsed: LandmassDef[] = raw.landmasses.map((lm) => ({
      id: lm.id,
      polygon: lm.polygon.map(([x, y]) => ({ x, y })),
      bbox: {
        minX: lm.bbox[0],
        minY: lm.bbox[1],
        maxX: lm.bbox[2],
        maxY: lm.bbox[3],
      } as LandmassBbox,
    }));

    setLandmasses(parsed);
    this.osmCities = raw.osmCities ?? [];
    console.log(`Loaded ${parsed.length} landmasses, ${this.osmCities.length} OSM cities`);
  }

  private createTilemap(): void {
    // All packs use OSM procedural rendering for now
    const mapW = 3200;
    const mapH = 2400;

    // Deep blue water background
    const bg = this.add.graphics();
    bg.setDepth(-1000);
    bg.fillStyle(0x0c2340, 1);
    bg.fillRect(0, 0, mapW, mapH);

    // Draw landmasses from polygon data (matches collision exactly)
    const landGfx = this.add.graphics();
    landGfx.setDepth(-900);
    for (const lm of LANDMASSES) {
      if (lm.polygon.length < 3) continue;
      // Filled green land
      landGfx.fillStyle(0x2d6a1e, 1);
      landGfx.beginPath();
      landGfx.moveTo(lm.polygon[0].x, lm.polygon[0].y);
      for (let i = 1; i < lm.polygon.length; i++) {
        landGfx.lineTo(lm.polygon[i].x, lm.polygon[i].y);
      }
      landGfx.closePath();
      landGfx.fillPath();
      // Yellow/sand coastline outline
      landGfx.lineStyle(1.5, 0xc8a84e, 0.8);
      landGfx.beginPath();
      landGfx.moveTo(lm.polygon[0].x, lm.polygon[0].y);
      for (let i = 1; i < lm.polygon.length; i++) {
        landGfx.lineTo(lm.polygon[i].x, lm.polygon[i].y);
      }
      landGfx.closePath();
      landGfx.strokePath();
    }

    // Build land grid from polygons for navigation/seagulls
    const CELL = 32;
    const cols = Math.ceil(mapW / CELL);
    const rows = Math.ceil(mapH / CELL);
    this.landGrid = Array.from({ length: rows }, () => Array(cols).fill(false));
    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) {
        const px = c * CELL + CELL / 2;
        const py = r * CELL + CELL / 2;
        const pt = { x: px, y: py };
        for (const lm of LANDMASSES) {
          if (pointInLandmass(pt, lm)) {
            this.landGrid[r][c] = true;
            break;
          }
        }
      }
    }
  }

  /** Generate 16x12 pixel flag textures for each faction (XVII century historical designs). */
  private generateFlagTextures(): void {
    const W = 16, H = 12;

    // England: St George's Cross (red cross on white)
    {
      const g = this.make.graphics({ x: 0, y: 0 });
      g.fillStyle(0xffffff, 1); g.fillRect(0, 0, W, H);
      g.fillStyle(0xcc0000, 1);
      g.fillRect(0, 5, W, 2);  // horizontal
      g.fillRect(7, 0, 2, H);  // vertical
      g.generateTexture("flag_england", W, H);
      g.destroy();
    }

    // Spain: Cross of Burgundy (red diagonal X on white, XVII century)
    {
      const g = this.make.graphics({ x: 0, y: 0 });
      g.fillStyle(0xffffff, 1); g.fillRect(0, 0, W, H);
      g.lineStyle(2, 0xcc0000, 1);
      g.beginPath();
      g.moveTo(1, 1); g.lineTo(W - 1, H - 1);
      g.strokePath();
      g.beginPath();
      g.moveTo(W - 1, 1); g.lineTo(1, H - 1);
      g.strokePath();
      // Thicken with second pass slightly offset
      g.lineStyle(1, 0xaa0000, 0.6);
      g.beginPath();
      g.moveTo(2, 0); g.lineTo(W, H - 2);
      g.strokePath();
      g.beginPath();
      g.moveTo(W - 2, 0); g.lineTo(0, H - 2);
      g.strokePath();
      g.generateTexture("flag_spain", W, H);
      g.destroy();
    }

    // France: Fleur-de-lis (gold lily on blue, pre-revolution)
    {
      const g = this.make.graphics({ x: 0, y: 0 });
      g.fillStyle(0x224488, 1); g.fillRect(0, 0, W, H);
      // Simplified fleur-de-lis: central stem + side petals
      g.fillStyle(0xffd700, 1);
      g.fillRect(7, 2, 2, 8);  // central stem
      g.fillRect(5, 3, 6, 2);  // cross bar
      // Top petals
      g.fillRect(4, 2, 2, 3);
      g.fillRect(10, 2, 2, 3);
      // Bottom flare
      g.fillRect(5, 8, 2, 2);
      g.fillRect(9, 8, 2, 2);
      g.generateTexture("flag_france", W, H);
      g.destroy();
    }

    // Netherlands: Prinsenvlag (orange-white-blue, XVII century)
    {
      const g = this.make.graphics({ x: 0, y: 0 });
      g.fillStyle(0xff7700, 1); g.fillRect(0, 0, W, 4);   // orange
      g.fillStyle(0xffffff, 1); g.fillRect(0, 4, W, 4);   // white
      g.fillStyle(0x2255aa, 1); g.fillRect(0, 8, W, 4);   // blue
      g.generateTexture("flag_netherlands", W, H);
      g.destroy();
    }

    // Pirates: Jolly Roger (white skull on black)
    {
      const g = this.make.graphics({ x: 0, y: 0 });
      g.fillStyle(0x111111, 1); g.fillRect(0, 0, W, H);
      // Skull (simplified)
      g.fillStyle(0xffffff, 1);
      g.fillRect(5, 2, 6, 5);   // skull body
      g.fillRect(6, 1, 4, 1);   // top of skull
      // Eyes
      g.fillStyle(0x111111, 1);
      g.fillRect(6, 3, 2, 2);
      g.fillRect(9, 3, 2, 2);
      // Crossbones
      g.lineStyle(1, 0xffffff, 0.9);
      g.beginPath();
      g.moveTo(3, 8); g.lineTo(13, 11);
      g.strokePath();
      g.beginPath();
      g.moveTo(13, 8); g.lineTo(3, 11);
      g.strokePath();
      g.generateTexture("flag_pirates", W, H);
      g.destroy();
    }
  }

  /** Generate a simple 4-direction crew party spritesheet (16x16 per frame, 4 frames). */
  private generateCrewTexture(): void {
    if (this.textures.exists("crew_party")) return;
    const FW = 16, FH = 16;
    const g = this.make.graphics({ x: 0, y: 0 });

    // 4 frames side by side: S, W, E, N (each 16x16)
    for (let f = 0; f < 4; f++) {
      const ox = f * FW;
      // 3 small pirate figures in a group
      for (let p = 0; p < 3; p++) {
        const px = ox + 3 + p * 5;
        const py = 4 + (p === 1 ? -2 : 0);

        // Body
        g.fillStyle(p === 0 ? 0x8b4513 : p === 1 ? 0xcc3333 : 0x2244aa, 1);
        g.fillRect(px, py + 4, 3, 5);

        // Head
        g.fillStyle(0xddbb88, 1);
        g.fillRect(px, py + 1, 3, 3);

        // Hat
        g.fillStyle(0x222222, 1);
        g.fillRect(px - 1, py, 5, 2);

        // Legs (direction-dependent offset)
        g.fillStyle(0x444444, 1);
        if (f === 0) { // S — walking down
          g.fillRect(px, py + 9, 1, 3);
          g.fillRect(px + 2, py + 9, 1, 3);
        } else if (f === 3) { // N — walking up
          g.fillRect(px, py + 9, 1, 2);
          g.fillRect(px + 2, py + 9, 1, 2);
        } else { // W/E — side view
          g.fillRect(px, py + 9, 1, 3);
          g.fillRect(px + 1, py + 9, 1, 2);
        }

        // Weapon (cutlass or musket)
        if (p === 0) {
          g.fillStyle(0xcccccc, 1);
          g.fillRect(px + 3, py + 5, 1, 4);
        }
      }
    }

    g.generateTexture("crew_party", FW * 4, FH);
    g.destroy();

    // Register as spritesheet
    const tex = this.textures.get("crew_party");
    tex.add(0, 0, 0, 0, FW, FH);   // S
    tex.add(1, 0, FW, 0, FW, FH);   // W
    tex.add(2, 0, FW * 2, 0, FW, FH); // E
    tex.add(3, 0, FW * 3, 0, FW, FH); // N
  }

  private toggleLandMode(): void {
    const playerEntity = this.worldState.entities[this.worldState.player.shipId as string];
    if (!playerEntity) return;

    // L key only used to embark (return to ship) — disembark is automatic on land collision
    if (playerEntity.mode === "landed") {
      this.commandQueue.push({ type: "Embark" });
    }
  }

  private createTerrainQuery(): (wx: number, wy: number) => TerrainType {
    return (wx: number, wy: number): TerrainType => {
      if (wx < 0 || wy < 0 || wx > 3200 || wy > 2400) {
        return "land";
      }

      const pt = { x: wx, y: wy };
      for (const lm of LANDMASSES) {
        if (pointInLandmass(pt, lm)) {
          return "land";
        }
      }
      return "sea";
    };
  }

  /**
   * Snap a port position to the nearest coastal land cell.
   * A coastal cell is a land cell in landGrid that has at least one water neighbor.
   * This guarantees: (1) the port is on land, (2) ships can reach it from water.
   */
  private snapToCoast(pos: { x: number; y: number }): { x: number; y: number } {
    const CELL = 32;
    const rows = this.landGrid.length;
    const cols = this.landGrid[0]?.length ?? 0;

    const isCoastal = (r: number, c: number): boolean => {
      if (!this.landGrid[r][c]) return false; // must be land
      // Check 4-neighbors for water
      for (const [dr, dc] of [[-1, 0], [1, 0], [0, -1], [0, 1]]) {
        const nr = r + dr, nc = c + dc;
        if (nr < 0 || nr >= rows || nc < 0 || nc >= cols) return true; // map edge = water
        if (!this.landGrid[nr][nc]) return true;
      }
      return false;
    };

    // BFS outward from the port's grid cell to find the nearest coastal land cell
    const startCol = Math.floor(pos.x / CELL);
    const startRow = Math.floor(pos.y / CELL);
    const clampR = (r: number) => Math.max(0, Math.min(rows - 1, r));
    const clampC = (c: number) => Math.max(0, Math.min(cols - 1, c));
    const sr = clampR(startRow), sc = clampC(startCol);

    // Quick check: already on a coastal cell
    if (isCoastal(sr, sc)) return pos;

    const visited = new Set<number>();
    const key = (r: number, c: number) => r * cols + c;
    const queue: [number, number][] = [[sr, sc]];
    visited.add(key(sr, sc));

    let bestR = sr, bestC = sc;
    let bestDist = Infinity;
    const MAX_SEARCH = 30; // max BFS radius in cells

    let head = 0;
    while (head < queue.length) {
      const [cr, cc] = queue[head++];
      const dist = Math.abs(cr - sr) + Math.abs(cc - sc);
      if (dist > MAX_SEARCH) continue;

      if (isCoastal(cr, cc)) {
        // Pick the coastal cell closest to original position (Euclidean)
        const cx = cc * CELL + CELL / 2;
        const cy = cr * CELL + CELL / 2;
        const d = (pos.x - cx) ** 2 + (pos.y - cy) ** 2;
        if (d < bestDist) {
          bestDist = d;
          bestR = cr;
          bestC = cc;
        }
        // Don't expand beyond found coastal cells at this distance
        if (dist < MAX_SEARCH) {
          // Keep searching at same distance for closer Euclidean match
        }
        continue; // don't expand past coastal cells
      }

      for (const [dr, dc] of [[-1, 0], [1, 0], [0, -1], [0, 1]]) {
        const nr = cr + dr, nc = cc + dc;
        if (nr < 0 || nr >= rows || nc < 0 || nc >= cols) continue;
        const k = key(nr, nc);
        if (visited.has(k)) continue;
        visited.add(k);
        queue.push([nr, nc]);
      }
    }

    if (bestDist < Infinity) {
      return { x: bestC * CELL + CELL / 2, y: bestR * CELL + CELL / 2 };
    }
    return pos; // fallback
  }

  /** Convert lon/lat to pixel coordinates (same Mercator formula as cities.ts geoToMap). */
  private geoToPixel(lon: number, lat: number): { x: number; y: number } {
    const mercYFn = (l: number) => Math.log(Math.tan(Math.PI / 4 + ((l * Math.PI) / 180) / 2));
    const yTop = mercYFn(35);
    const yBot = mercYFn(7);
    return {
      x: ((lon - (-100)) / 45) * 3200,
      y: ((yTop - mercYFn(lat)) / (yTop - yBot)) * 2400,
    };
  }

  private toggleGrid(): void {
    if (this.gridContainer) {
      this.gridContainer.destroy();
      this.gridContainer = null;
      return;
    }
    this.gridContainer = this.add.container(0, 0);
    this.gridContainer.setDepth(9000);

    const g = this.add.graphics();
    this.gridContainer.add(g);

    // Draw longitude lines (vertical) from 98°W to 56°W
    for (let lon = -98; lon <= -56; lon += 2) {
      const px = this.geoToPixel(lon, 0).x;
      const isMajor = (-lon) % 10 === 0;
      g.lineStyle(isMajor ? 1.5 : 0.5, 0xffffff, isMajor ? 0.5 : 0.2);
      g.lineBetween(px, 0, px, 2400);
      // Label
      const label = this.add.text(px, 4, `${-lon}°W`, {
        ...txt(isMajor ? 11 : 9, { color: "#ffffff" }),
        backgroundColor: "#00000088",
        padding: { x: 2, y: 1 },
      });
      label.setOrigin(0.5, 0);
      this.gridContainer.add(label);
    }

    // Draw latitude lines (horizontal) from 8°N to 34°N
    for (let lat = 8; lat <= 34; lat += 2) {
      const py = this.geoToPixel(0, lat).y;
      const isMajor = lat % 10 === 0;
      g.lineStyle(isMajor ? 1.5 : 0.5, 0xffffff, isMajor ? 0.5 : 0.2);
      g.lineBetween(0, py, 3200, py);
      // Label
      const label = this.add.text(4, py, `${lat}°N`, {
        ...txt(isMajor ? 11 : 9, { color: "#ffffff" }),
        backgroundColor: "#00000088",
        padding: { x: 2, y: 1 },
      });
      label.setOrigin(0, 0.5);
      this.gridContainer.add(label);
    }

    // Mark each port with its coordinate
    for (const [, port] of Object.entries(PORTS)) {
      const px = port.pos.x;
      const py = port.pos.y;
      // Reverse-calculate lon/lat from pixel position (Mercator inverse)
      const lon = (px / 3200) * 45 + (-100);
      // For lat, we need inverse Mercator — approximate with display
      const mercYFn = (l: number) => Math.log(Math.tan(Math.PI / 4 + ((l * Math.PI) / 180) / 2));
      const yTop = mercYFn(35);
      const yBot = mercYFn(7);
      const mercLat = yTop - (py / 2400) * (yTop - yBot);
      const lat = (2 * Math.atan(Math.exp(mercLat)) - Math.PI / 2) * 180 / Math.PI;
      const coordLabel = this.add.text(px, py + 14, `${(-lon).toFixed(1)}°W ${lat.toFixed(1)}°N`, {
        ...txt(8, { color: "#ffff00" }),
        backgroundColor: "#000000aa",
        padding: { x: 2, y: 1 },
      });
      coordLabel.setOrigin(0.5, 0);
      this.gridContainer.add(coordLabel);
    }
  }

  private drawPortMarkers(): void {
    const g = this.add.graphics();
    g.setDepth(500);

    for (const [portKey, port] of Object.entries(PORTS)) {
      // Snap port to nearest coastal land cell — used for rendering AND dock interaction
      const safePos = this.snapToCoast(port.pos);
      this.portSafePositions.set(portKey, safePos);
      const drawPort = { ...port, pos: safePos };

      this.drawCityIcon(g, drawPort);

      // Add historical flag sprite next to city
      const factionId = port.factionId as string;
      const flagKey = `flag_${factionId}`;
      if (this.textures.exists(flagKey)) {
        const flagX = safePos.x + (port.type === "fort" ? -12 : 14);
        const flagY = safePos.y - (port.population === "large" || port.population === "capital" ? 18 : 12);
        const flagImg = this.add.image(flagX, flagY, flagKey);
        flagImg.setDepth(501);
        flagImg.setScale(0.5);
        // Waving animation
        this.tweens.add({
          targets: flagImg,
          angle: { from: -3, to: 3 },
          ease: "Sine.easeInOut",
          duration: 1500,
          yoyo: true,
          repeat: -1,
        });
      }

      const isLarge = port.population === "large" || port.population === "capital";
      const labelSize = isLarge ? 14 : port.population === "medium" ? 12 : 10;
      const labelY = port.type === "fort"
        ? safePos.y - (isLarge ? 30 : 22)
        : safePos.y - (isLarge ? 36 : port.population === "medium" ? 28 : 18);

      const label = this.add.text(safePos.x, labelY, t("port." + portKey + ".name"), {
        ...txt(labelSize, { bold: true }),
        stroke: "#ffffff",
        strokeThickness: 2,
      });
      label.setOrigin(0.5, 1);
      label.setDepth(500);
    }
  }

  private drawOSMCityLabels(): void {
    if (this.osmCities.length === 0) return;

    // Collect gameplay port positions for dedup
    const portPositions = Object.values(PORTS).map((p) => p.pos);
    const DEDUP_DIST = 60;
    const MAX_LABELS = 200; // cap to avoid performance issues
    const LABEL_SPACING = 40; // minimum distance between OSM labels

    // Only draw cities that are on land (skip offshore points)
    const onLandCities = this.osmCities.filter((city) => {
      const pt = { x: city.x, y: city.y };
      for (const lm of LANDMASSES) {
        if (pointInLandmass(pt, lm)) return true;
      }
      return false;
    });

    // Sort by a rough importance heuristic (name length as proxy — shorter = more important)
    onLandCities.sort((a, b) => a.name.length - b.name.length);

    const placed: Array<{ x: number; y: number }> = [];
    let drawn = 0;

    for (const city of onLandCities) {
      if (drawn >= MAX_LABELS) break;

      // Skip cities too close to gameplay ports
      const tooCloseToPort = portPositions.some(
        (pp) => Math.abs(pp.x - city.x) < DEDUP_DIST && Math.abs(pp.y - city.y) < DEDUP_DIST,
      );
      if (tooCloseToPort) continue;

      // Skip cities too close to already-placed labels
      const tooCloseToLabel = placed.some(
        (pp) => Math.abs(pp.x - city.x) < LABEL_SPACING && Math.abs(pp.y - city.y) < LABEL_SPACING,
      );
      if (tooCloseToLabel) continue;

      const label = this.add.text(city.x, city.y, city.name, {
        ...txt(7, { color: "#bbaa88" }),
        stroke: "#000000",
        strokeThickness: 1,
      });
      label.setOrigin(0.5, 0.5);
      label.setDepth(400);
      placed.push({ x: city.x, y: city.y });
      drawn++;
    }
  }

  private drawCityIcon(g: Phaser.GameObjects.Graphics, port: PortDef): void {
    const x = port.pos.x;
    const y = port.pos.y;
    const factionDef = FACTIONS[port.factionId as string];
    const flagColor = factionDef?.color ?? 0xaaaaaa;
    const pop = port.population;

    // Try AI-generated city sprite first (not for forts)
    if (port.type !== "fort") {
      let spriteKey: string | null = null;
      if ((pop === "large" || pop === "capital") && this.textures.exists("city_large")) {
        spriteKey = "city_large";
      } else if (pop === "medium" && this.textures.exists("city_medium")) {
        spriteKey = "city_medium";
      } else if (this.textures.exists("city_small")) {
        spriteKey = "city_small";
      }

      if (spriteKey) {
        const cityImg = this.add.image(x, y, spriteKey);
        cityImg.setDepth(500);
        const scale = pop === "large" || pop === "capital" ? 0.8 : pop === "medium" ? 0.65 : 0.5;
        cityImg.setScale(scale);
        return;
      }
    }

    // Fallback: procedural drawing
    if (port.type === "fort") {
      this.drawFort(g, x, y, flagColor, pop);
    } else if (pop === "large" || pop === "capital") {
      this.drawCityLarge(g, x, y, flagColor);
    } else if (pop === "medium") {
      this.drawCityMedium(g, x, y, flagColor);
    } else {
      this.drawCitySmall(g, x, y, flagColor);
    }
  }

  /** Large city: walled town with church, multiple buildings, prominent flag */
  private drawCityLarge(g: Phaser.GameObjects.Graphics, x: number, y: number, _flagColor: number): void {
    // City wall base
    g.fillStyle(0x8a7a5a, 1);
    g.fillRect(x - 18, y + 2, 36, 4);
    // Wall crenellations
    g.fillStyle(0x7a6a4a, 1);
    for (let i = -17; i <= 15; i += 4) {
      g.fillRect(x + i, y - 1, 3, 3);
    }

    // Left building
    g.fillStyle(0xc9a855, 1);
    g.fillRect(x - 14, y - 8, 8, 10);
    g.fillStyle(0x8b4513, 1);
    g.fillTriangle(x - 15, y - 8, x - 5, y - 8, x - 10, y - 13);

    // Central tall building (town hall)
    g.fillStyle(0xb89845, 1);
    g.fillRect(x - 4, y - 12, 9, 14);
    g.fillStyle(0x8b4513, 1);
    g.fillTriangle(x - 5, y - 12, x + 6, y - 12, x + 0.5, y - 17);

    // Right building
    g.fillStyle(0xc9a855, 1);
    g.fillRect(x + 7, y - 6, 7, 8);
    g.fillStyle(0x8b4513, 1);
    g.fillTriangle(x + 6, y - 6, x + 15, y - 6, x + 10.5, y - 10);

    // Church tower (tallest element)
    g.fillStyle(0xd4b96a, 1);
    g.fillRect(x - 1, y - 22, 3, 10);
    g.fillStyle(0xccaa55, 1);
    g.fillTriangle(x - 2, y - 22, x + 3, y - 22, x + 0.5, y - 26);
    // Cross on top
    g.lineStyle(1, 0xffdd44, 0.9);
    g.lineBetween(x + 0.5, y - 26, x + 0.5, y - 29);
    g.lineBetween(x - 1, y - 28, x + 2, y - 28);

    // Windows (lit)
    g.fillStyle(0xffdd44, 0.7);
    g.fillRect(x - 12, y - 6, 2, 2);
    g.fillRect(x - 9, y - 6, 2, 2);
    g.fillRect(x - 2, y - 10, 2, 2);
    g.fillRect(x + 2, y - 10, 2, 2);
    g.fillRect(x - 2, y - 6, 2, 2);
    g.fillRect(x + 2, y - 6, 2, 2);
    g.fillRect(x + 9, y - 4, 2, 2);

    // Doors
    g.fillStyle(0x443322, 1);
    g.fillRect(x - 1, y - 2, 3, 4);
    g.fillRect(x - 11, y - 2, 3, 4);

    // Flag pole (right side) — flag sprite added separately in drawPortMarkers
    g.lineStyle(1, 0xdddddd, 0.9);
    g.lineBetween(x + 14, y - 6, x + 14, y - 16);
  }

  /** Medium city: 2-3 buildings with roofs, flag */
  private drawCityMedium(g: Phaser.GameObjects.Graphics, x: number, y: number, _flagColor: number): void {
    // Left building
    g.fillStyle(0xc9a855, 1);
    g.fillRect(x - 9, y - 4, 7, 7);
    g.fillStyle(0x8b4513, 1);
    g.fillTriangle(x - 10, y - 4, x - 1, y - 4, x - 5.5, y - 8);

    // Central building (taller)
    g.fillStyle(0xb89845, 1);
    g.fillRect(x - 1, y - 7, 6, 10);
    g.fillStyle(0x8b4513, 1);
    g.fillTriangle(x - 2, y - 7, x + 6, y - 7, x + 2, y - 12);

    // Tower/steeple
    g.fillStyle(0xd4b96a, 1);
    g.fillRect(x + 1, y - 16, 2, 4);
    g.fillStyle(0xccaa55, 1);
    g.fillTriangle(x, y - 16, x + 4, y - 16, x + 2, y - 19);

    // Right small structure
    g.fillStyle(0xc9a855, 1);
    g.fillRect(x + 6, y - 2, 5, 5);
    g.fillStyle(0x8b4513, 1);
    g.fillTriangle(x + 5, y - 2, x + 12, y - 2, x + 8.5, y - 5);

    // Windows
    g.fillStyle(0xffdd44, 0.7);
    g.fillRect(x - 7, y - 2, 2, 2);
    g.fillRect(x + 1, y - 5, 2, 2);
    g.fillRect(x + 1, y - 1, 2, 2);

    // Door
    g.fillStyle(0x443322, 1);
    g.fillRect(x + 1, y + 1, 2, 2);

    // Flag pole — flag sprite added separately in drawPortMarkers
    g.lineStyle(1, 0xdddddd, 0.8);
    g.lineBetween(x + 9, y - 2, x + 9, y - 10);
  }

  /** Small settlement: 1-2 huts, tiny flag */
  private drawCitySmall(g: Phaser.GameObjects.Graphics, x: number, y: number, _flagColor: number): void {
    // Main hut
    g.fillStyle(0x8b7355, 1);
    g.fillRect(x - 5, y - 2, 6, 5);
    g.fillStyle(0x556633, 1);
    g.fillTriangle(x - 6, y - 2, x + 2, y - 2, x - 2, y - 6);

    // Second small hut
    g.fillStyle(0x8b7355, 1);
    g.fillRect(x + 2, y - 1, 5, 4);
    g.fillStyle(0x556633, 1);
    g.fillTriangle(x + 1, y - 1, x + 8, y - 1, x + 4.5, y - 4);

    // Dock/pier
    g.fillStyle(0x8b6b40, 0.8);
    g.fillRect(x - 1, y + 3, 2, 5);
    g.fillRect(x - 3, y + 7, 6, 2);

    // Small flag pole — flag sprite added separately in drawPortMarkers
    g.lineStyle(1, 0xaaaaaa, 0.8);
    g.lineBetween(x - 3, y - 2, x - 3, y - 10);
  }

  /** Fort: stone walls with towers, scales by population */
  private drawFort(g: Phaser.GameObjects.Graphics, x: number, y: number, _flagColor: number, pop: string): void {
    const big = pop === "large" || pop === "capital" || pop === "medium";
    const s = big ? 1.2 : 1.0;

    // Main wall
    g.fillStyle(0x777777, 1);
    g.fillRect(x - 9 * s, y - 7 * s, 18 * s, 14 * s);

    // Corner towers
    g.fillStyle(0x666666, 1);
    g.fillRect(x - 11 * s, y - 9 * s, 5 * s, 5 * s);
    g.fillRect(x + 6 * s, y - 9 * s, 5 * s, 5 * s);
    g.fillRect(x - 11 * s, y + 4 * s, 5 * s, 5 * s);
    g.fillRect(x + 6 * s, y + 4 * s, 5 * s, 5 * s);

    // Battlements
    g.fillStyle(0x888888, 1);
    for (let i = -10 * s; i <= 8 * s; i += 3 * s) {
      g.fillRect(x + i, y - 11 * s, 2 * s, 2 * s);
    }

    // Gate
    g.fillStyle(0x443322, 1);
    g.fillRect(x - 2 * s, y + 2 * s, 4 * s, 5 * s);

    // Gate arch
    g.lineStyle(1, 0x555555, 0.8);
    g.strokeRect(x - 2 * s, y + 2 * s, 4 * s, 5 * s);

    // Flag pole — flag sprite added separately in drawPortMarkers
    g.lineStyle(1, 0xdddddd, 0.9);
    g.lineBetween(x - 9 * s, y - 9 * s, x - 9 * s, y - 16 * s);

    if (big) {
      // Extra detail for larger forts: cannon positions
      g.fillStyle(0x333333, 1);
      g.fillCircle(x - 8 * s, y - 6 * s, 1.5);
      g.fillCircle(x + 8 * s, y - 6 * s, 1.5);
      g.fillCircle(x - 8 * s, y + 6 * s, 1.5);
      g.fillCircle(x + 8 * s, y + 6 * s, 1.5);
    }
  }

  private findNearPort(): (typeof PORTS)[keyof typeof PORTS] | null {
    const playerEntity = this.worldState.entities[this.worldState.player.shipId as string];
    if (!playerEntity) return null;

    const isLanded = playerEntity.mode === "landed";
    const radius = isLanded ? 45 : 15;

    for (const [portKey, port] of Object.entries(PORTS)) {
      // Use coast-snapped position (on land, adjacent to water) for all checks
      const checkPos = this.portSafePositions.get(portKey) ?? port.pos;
      const dist = vec2Dist(playerEntity.pos, checkPos);
      if (dist <= radius) {
        return port;
      }
    }
    return null;
  }

  private openPortDialog(port: PortDef): void {
    this.portDialogOpen = true;
    const portKey = Object.entries(PORTS).find(([_, p]) => p === port)?.[0];
    if (!portKey) return;

    // Stop the ship when approaching a port from sea
    const playerEntity = this.worldState.entities[this.worldState.player.shipId as string];
    if (playerEntity && playerEntity.mode !== "landed") {
      const shipId = this.worldState.player.shipId as string;
      this.worldState = {
        ...this.worldState,
        entities: {
          ...this.worldState.entities,
          [shipId]: {
            ...playerEntity,
            vel: { x: 0, y: 0 },
            sailLevel: 0,
          },
        },
      };
      this.registry.set("worldState", this.worldState);
    }

    this.scene.launch("PortApproachScene", {
      worldState: this.worldState,
      portId: portKey,
    });
    this.time.delayedCall(0, () => {
      this.scene.pause();
    });
  }

  update(_time: number, delta: number): void {
    // Sync input mode with entity mode
    const pe = this.worldState.entities[this.worldState.player.shipId as string];
    this.inputMapper.setLandedMode(pe?.mode === "landed", pe?.sailLevel);
    this.inputMapper.update();

    // Mouse steering: hold left button to steer toward cursor
    this.updateMouseSteering(pe);

    // Game speed multiplier scales the effective simulation rate
    const speedMultiplier = this.worldState.gameSpeed ?? 1.2;
    this.tickAccumulator += delta * speedMultiplier;

    while (this.tickAccumulator >= TICK_MS) {
      this.tickAccumulator -= TICK_MS;

      const commands = this.commandQueue.drain();
      const result = this.engine.apply(this.worldState, commands, 1);
      this.worldState = result.state;
      this.registry.set("worldState", this.worldState);

      if (result.events.length > 0) {
        this.worldRenderer.applyEvents(this, result.events);
      }

      if (result.transitions) {
        for (const t of result.transitions) {
          this.handleTransition(t);
          return;
        }
      }
    }

    this.worldRenderer.sync(this, this.worldState);

    const playerEntity = this.worldState.entities[this.worldState.player.shipId as string];
    if (playerEntity) {
      this.cameraCtrl.setTarget(playerEntity.pos);
      this.cameraCtrl.update();
    }

    this.minimap.update(this, this.worldState);
    this.cloudRenderer.update(this.worldState.weather.windDirRad, this.worldState.weather.windStrength);
    this.seagullRenderer.update(this.worldState.weather.windDirRad, this.worldState.weather.windStrength);
    this.windCompass.update(this.worldState.weather.windDirRad, this.worldState.weather.windStrength);

    // Scroll water tile with wind
    if (this.waterTileSprite) {
      const windDir = this.worldState.weather.windDirRad;
      const str = this.worldState.weather.windStrength;
      this.waterTileSprite.tilePositionX += Math.sin(windDir) * 0.15 * str;
      this.waterTileSprite.tilePositionY += -Math.cos(windDir) * 0.15 * str;
    }

    // Wind sound volume follows wind strength
    if (this.windSound && "setVolume" in this.windSound) {
      (this.windSound as Phaser.Sound.WebAudioSound).setVolume(
        this.worldState.weather.windStrength * 0.6,
      );
    }

    // Auto-embark: when crew walks very close to the anchored ship, board automatically
    if (playerEntity?.mode === "landed" && playerEntity.anchorPos) {
      const distToShip = vec2Dist(playerEntity.pos, playerEntity.anchorPos);
      if (distToShip < 20) {
        this.commandQueue.push({ type: "Embark" });
      }
    }

    this.updateHud();
    this.updatePortPrompt();
  }

  /** Steer ship/crew toward mouse cursor while left button is held. */
  private updateMouseSteering(playerEntity: { pos: { x: number; y: number }; heading: number; mode: string; sailLevel: number } | undefined): void {
    if (!playerEntity) return;
    const pointer = this.input.activePointer;
    if (!pointer.isDown || pointer.button !== 0) return;

    // Convert screen coordinates to world coordinates
    const cam = this.cameras.main;
    const worldX = pointer.x / cam.zoom + cam.scrollX;
    const worldY = pointer.y / cam.zoom + cam.scrollY;

    const dx = worldX - playerEntity.pos.x;
    const dy = worldY - playerEntity.pos.y;
    const dist = Math.sqrt(dx * dx + dy * dy);
    if (dist < 5) return; // too close, ignore

    // heading: 0=N, PI/2=E, PI=S — atan2(dx, -dy) matches this convention
    const targetHeading = Math.atan2(dx, -dy);

    if (playerEntity.mode === "landed") {
      // Land mode: set heading and walk
      this.commandQueue.push({ type: "SetHeading", heading: targetHeading });
      this.commandQueue.push({ type: "SetSailLevel", value: 1 });
    } else {
      // Sailing mode: set heading, raise sails if stopped
      this.commandQueue.push({ type: "SetHeading", heading: targetHeading });
      if (playerEntity.sailLevel === 0) {
        this.inputMapper.setSailLevel(0.34);
        this.commandQueue.push({ type: "SetSailLevel", value: 0.34 });
      }
    }
  }

  private updateHud(): void {
    const player = this.worldState.player;
    const playerEntity = this.worldState.entities[player.shipId as string];

    // Date text (top-left, no background)
    const dateStr = formatCalendarDate(this.worldState.time, this.worldState.startYear);
    const hh = String(this.worldState.time.hour).padStart(2, "0");
    const mm = String(this.worldState.time.minute).padStart(2, "0");
    this.dateText.setText(`${dateStr}\n${hh}:${mm}`);

    // Compact HUD
    let line1 = `${t("hud.gold")}: ${player.gold}`;
    if (playerEntity?.ship) {
      line1 += `  |  ${t("hud.hull", { current: Math.round(playerEntity.ship.hullHp), max: playerEntity.ship.hullMax })}`;
      line1 += `  |  ${t("hud.crew", { current: playerEntity.ship.crew.current, max: playerEntity.ship.crew.max })}`;
    }

    const isLanded = playerEntity?.mode === "landed";
    const sailPct = ((playerEntity?.sailLevel ?? 0) * 100).toFixed(0);
    const speedStr = playerEntity
      ? t("hud.speed", { value: Math.round(Math.sqrt(playerEntity.vel.x ** 2 + playerEntity.vel.y ** 2) * 100) / 100 })
      : "";
    const controlsKey = isLanded ? "hud.controls_land" : "hud.controls";
    const modePrefix = isLanded ? `[${t("hud.mode_land")}]  ` : "";
    const line2 = `${modePrefix}${t("hud.sail_pct", { pct: sailPct })}  |  ${speedStr}  |  ${t(controlsKey)}`;

    this.hudText.setText(`${line1}\n${line2}`);
  }

  private updatePortPrompt(): void {
    const playerEntity = this.worldState.entities[this.worldState.player.shipId as string];

    // Check for nearby port — works in BOTH sailing and landed modes
    const nearPort = this.findNearPort();
    if (nearPort) {
      if (!this.wasNearPort && !this.portDialogOpen) {
        this.openPortDialog(nearPort);
      }
      this.wasNearPort = true;
      const promptPortKey = Object.entries(PORTS).find(([_, p]) => p === nearPort)?.[0] ?? "";
      this.portPromptText!.setText(t("approach.prompt", { name: t("port." + promptPortKey + ".name") }));
      this.portPromptText!.setVisible(!this.portDialogOpen);
      return;
    }

    this.wasNearPort = false;

    // Landed mode: show ship boarding prompt when near anchor
    if (playerEntity?.mode === "landed" && playerEntity.anchorPos) {
      const distToShip = vec2Dist(playerEntity.pos, playerEntity.anchorPos);
      if (distToShip < 50) {
        this.portPromptText!.setText(t("hud.embark_ship_prompt"));
        this.portPromptText!.setVisible(true);
        return;
      }
      // Far from ship: show general embark hint
      this.portPromptText!.setText(t("hud.embark_prompt"));
      this.portPromptText!.setVisible(true);
      return;
    }

    this.portPromptText!.setVisible(false);
  }

  private handleTransition(t: Transition): void {
    const payload = t.payload as Record<string, unknown> | undefined;
    switch (t.scene) {
      case "Port":
        this.scene.start("PortScene", { worldState: this.worldState, portId: payload?.portId });
        break;
      case "SeaBattle":
        this.scene.start("SeaBattleScene", { worldState: this.worldState, enemyId: payload?.enemyId });
        break;
      default:
        break;
    }
  }

  shutdown(): void {
    if (this.onResize) {
      this.scale.off("resize", this.onResize);
      this.onResize = null;
    }
    this.worldRenderer.destroy();
    this.minimap.destroy();
    this.cloudRenderer.destroy();
    this.seagullRenderer.destroy();
    this.windCompass.destroy();
    this.inputMapper.destroy();
    if (this.windSound) {
      this.windSound.stop();
      this.windSound.destroy();
      this.windSound = null;
    }
  }
}
