export type ChangelogEntry = {
  version: string;
  date: string;
  changes: string[];
};

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "0.9.7.0",
    date: "2026-05-18",
    changes: [
      "LIVING ECONOMY — cities now grow, shrink, and react to world events",
      "  Numeric population, wealth (0-1000), and defence (0-100) per port",
      "  Daily economy tick: production → consumption → price update → recovery",
      "  Prices respond to supply/demand: shortages cost more, gluts cost less",
      "  CityInfo panel shows live values with ↑/↓ trend arrows vs baseline",
      "  CityInfo panel lists active world events affecting that port",
      "NEW WORLD EVENTS (Phase 2 — events now reshape the world):",
      "  Gold strike: small/medium town starts producing gold, pop +0.5%/day for a year",
      "  Indigenous raid: Spanish frontier outposts lose pop, wealth, defence",
      "  Famine: food/water prices ×2-4, population drops",
      "  Harvest (autumn): food/sugar prices ×0.6, +inventory boost",
      "  Royal decree: faction-wide tariff change, lasts up to a year",
      "EVENT EFFECTS — every event now applies daily state deltas:",
      "  Epidemic → population drop, crew recruitment halved, prices spike",
      "  Pirate raid (one-shot) → wealth -80, inventory -30%, defence decays",
      "  Hurricane → port closed, inventory damage, ships hit",
      "  Trade boom → production ×1.5, prices -20%",
      "  Slave revolt → production ×0.3, wealth drains",
      "  New governor → wealth windfall +50",
      "WAR DRIVES SEA TRAFFIC:",
      "  Warring factions spawn 2× more ships",
      "  Wartime spawns shift 45% → 70% navy, trader share drops",
      "  Production -15% / prices +10% in warring nations",
      "Migration v7 for old saves — fills new numeric fields from baseline",
      "i18n: 6 new news headline keys (EN + PL)",
    ],
  },
  {
    version: "0.9.6.0",
    date: "2026-05-11",
    changes: [
      "SEA BATTLES — Sid Meier's Pirates! style combat scene",
      "  ?battle=1|trader|navy|pirate|hunter URL params for direct testing",
      "  Camera follows player (always centered), arena 3× viewport",
      "  Manual broadsides: Q (port) / E (starboard), arc-restricted (no fore/aft)",
      "  3 ammo types: 1=Round, 2=Chain, 3=Grape — switching resets reload",
      "  Flying cannonballs with parabolic arc, splash on miss/overshoot",
      "  Cannon range = half screen; visible port + starboard arc indicators",
      "  Per-cannon damage scaling: broadside = ship.cannons / 2",
      "  Hull armor per ship class (Galleon 0.60 thick → Sloop 0.10 paper)",
      "  Quadratic distance falloff + ×1.6 point-blank bonus + accuracy roll",
      "  Wind- and hull-modulated steering (damaged hull = sluggish rudder)",
      "  Sail level affects speed; W/S cycles Furled / Battle / Full",
      "  9-second reload per broadside, color-coded L (red) / R (green) bars",
      "  AI archetypes: aggressive / defensive / tactical; crew-ratio override",
      "  Enemy with ≥1.5× player crew aims to board; ≤0.5× tries to flee",
      "  Boarding (B) when enemy weakened; capture adds ship to fleet",
      "  Auto-surrender at hull ≤10% OR sails ≤10% OR crew <10",
      "  60s far-distance → 60s countdown → auto-disengage",
      "  Battle Help (H) — in-battle manual with full damage formula spec",
      "  HUD top-right: ammo / sails / speed (kn) / cannons",
      "  Under each ship: hull/sails bars + crew & cannon counts + reload",
      "  Damage floaters: hull (red) / sails (cyan) / crew (orange), 2s",
      "  Outcomes apply to world: damage, loot, capture, reputation",
    ],
  },
  {
    version: "0.9.5.0",
    date: "2026-03-28",
    changes: [
      "9 ship classes: Pinnace, Sloop, Barque, Brigantine, Fluyt, Frigate, Fast Galleon, Galleon, Merchantman",
      "Fleet system: max 3 ships, buy/sell/abandon escorts in shipyard",
      "  Fleet speed = slowest ship, vision = tallest mast",
      "World Events: 10 historical wars (1568-1697) + 7 random event types",
      "NPC News: traders/navy carry news from ports, share on approach",
      "  Tavern rumors now include local world event news",
      "Seagull sounds: synthesized cries at zoom 5+ (Web Audio)",
      "Sail level affects turn rate: reefed = +50% maneuverability",
      "Spyglass range based on ship mast height (fleet max)",
      "Wind physics: peak 150% at beam reach, realistic polar diagram",
      "Help screen updated: 12 columns, all 9 ship classes with max knots + luneta range",
    ],
  },
  {
    version: "0.9.4.0",
    date: "2026-03-27",
    changes: [
      "Wind physics: realistic polar diagram with ship-specific dead zones",
      "  Sloop 35° (fore-and-aft), Brigantine 40°, Frigate 50°, Galleon 60°, Merchantman 55°",
      "  Dead zone → close hauled → beam reach (peak) → running",
      "  'Pod wiatr!' warning in UI when in irons",
      "Ship parameters: minWindAngle, mastHeight, rigType, tonnage, draft added",
      "Help screen (H key): 4 sections — Controls, Ships, Sailing, World",
      "  Ships table with all parameters, sailing guide with wind angles",
      "Ship speed display under sail level (knots)",
      "Wind label enlarged (14px)",
      "Sail transition: 3s → 2s",
    ],
  },
  {
    version: "0.9.3.1",
    date: "2026-03-26",
    changes: [
      "Sail system: 4 named levels (Furled/Reefed/Half/Full), 3s smooth transitions",
      "Sail UI: level name displayed under compass",
      "On-foot port visits: entering on foot → leaving returns on foot (no ship teleport)",
      "Port labels: 'ODEJDŹ' when on foot, 'ODPŁYŃ' when sailing (approach + port scenes)",
      "Port interaction radius reduced on foot (20→10px)",
      "Wake particles: 3× more, 50% shorter, tighter spread",
      "Wave overlay disabled (blocky) — replaced with photo-based parallax",
    ],
  },
  {
    version: "0.9.3.0",
    date: "2026-03-25",
    changes: [
      "FIX JITTER: root cause was Phaser pixelArt:true forcing roundPixels — camera.setRoundPixels(false)",
      "Variable timestep: 1 tick per frame, no accumulator (like seagulls/clouds)",
      "Wave overlay v2: photo-based parallax (two TileSprite layers, ADD blend, no canvas strokes)",
      "Integer zoom levels: scroll snaps to 1×–12× with smooth lerp transition",
      "Ship sprites: auto-cut from ChatGPT image, per-frame elliptical masks, white bg removed",
      "Crew party PNG sprite (pirate crew with skull flag)",
      "Fix instant re-embark (landedTick cooldown), turbo departure (pushDist 15→5, grace speed 1.5→0.15)",
      "Crew lands 3px from coast (was 20px deep inland)",
      "Disabled old wave overlay (blocky canvas strokes) — replaced with photo-based",
    ],
  },
  {
    version: "0.9.2.3",
    date: "2026-03-25",
    changes: [
      "New ship sprites: 8 directions from ChatGPT image, auto-cut with elliptical mask",
      "Ship sprite: white bg removed, 256x256 frames, LINEAR filtering",
      "Crew party PNG sprite (pirate crew with skull flag) replaces procedural rectangles",
      "Crew 2x bigger (12 world px), ship scale adjusted (0.086 for 256px frames)",
      "Fix instant re-embark: landedTick cooldown (15 ticks) + auto-embark radius 20→8px",
      "Fix turbo departure: grace speed 1.5→0.15, pushDist 15→5px, duration 40→15 ticks",
      "Crew lands 3px from coast (was 20px deep inland)",
      "City info panel: i18n refactor, fort info, shipyard types, last visit",
      "Port seagulls: 3-10 per port over water + reduced ambient (80-150)",
      "Fix ship directions (180° — ships faced inward in source image)",
    ],
  },
  {
    version: "0.9.2.2",
    date: "2026-03-24",
    changes: [
      "Ship speed halved: Sloop 0.30, Brigantine 0.275, Frigate 0.25, Galleon 0.19, Merchantman 0.16",
      "Smooth movement v5: velocity prediction with gameSpeed fix + softer drift correction (0.03)",
      "Embark: minimal sails (0.1) for slow departure from land",
      "Fix Petit Goâve + Léogane positions (were inland, moved to coast)",
      "TODO: sailing into wind = speed 0 (advanced wind physics deferred)",
    ],
  },
  {
    version: "0.9.2.1",
    date: "2026-03-23",
    changes: [
      "6 city PNG sprites: large/medium/small × city/fort (384×256, pre-scaled for sharpness)",
      "Cities 50% bigger on max zoom (22/15/10 world px)",
      "Smooth ship movement: exponential smoothing replaces fixed-timestep interpolation",
      "Camera direct follow (no lerp delay), delta cap for frame spike protection",
      "Wave layers: ADD blend mode (fixes blue rectangle artifacts)",
      "Wave visibility: zoom 6→12, 50% max alpha, blur for natural look",
      "Fix 5 cities on water: San Juan, Santa Catalina, Montserrat, Curaçao, Port de Paix",
      "Removed shore shadow canvas (caused pixelated squares at curves)",
      "Chaikin smoothing 3 iterations for smoother coastlines",
      "Original city assets preserved in sprites/originals/",
    ],
  },
  {
    version: "0.9.2.0",
    date: "2026-03-21",
    changes: [
      "Sea photo texture: mirror-tiled, zoom-dependent alpha (0→50%), depth under wave layers",
      "Land photo texture: tropical forest aerial, mirror-tiled, GeometryMask to land polygons",
      "City sprites: PNG assets (city_large.png), isometric colonial town, constant screen size",
      "Beach gradient: 3 GPU-rendered strokes with zoom fade, no pixelation",
      "Shore shadow: canvas shadowBlur for smooth Gaussian glow at coastline",
      "Flags: constant screen size at all zoom levels, LINEAR filtering",
      "City labels: constant screen size (1/zoom), no more growing at close zoom",
      "Ship scale: 33% smaller at max zoom",
      "Crew sprite: 10x smaller on land",
      "Turn rate: 3x faster key response (0.04 → 0.12 rad/tick)",
      "Start screen: new Barbados beach background, opaque BG fix",
      "Zoom indicator: bottom-left corner, normalized 0→10 scale",
      "URL debug params: ?skip, ?zoom=, ?debug= for testing",
      "Puerto Príncipe: moved east (was on water)",
      "Palm forest procedural generator (PalmForestTexture.ts) — ported from HTML tool",
    ],
  },
  {
    version: "0.9.0",
    date: "2026-03-20",
    changes: [
      "Volumetric clouds: spite codepen texture, layered clusters (10-20 layers), 3 size classes",
      "Cloud zoom scaling: shrink on zoom out, grow on zoom in",
      "Wind compass: procedural canvas-drawn (WindCompassWidget), no external images",
      "Ocean waves: mirror-tiled 2-layer parallax, animated with wind",
      "Ship speed halved, turn rate 4x, port departure with minimal sails",
      "Smooth coastlines: Chaikin subdivision on landmass polygons",
      "Vision circle restored (Arc), fog-of-war toggle in Options",
      "Debug toggle in Options (default ON), LPM disabled while sailing",
      "Date moved to top-left corner",
      "Ship wake: animated arc ripples around moving ships",
      "Refactor: MainMapScene 1327→739 lines (TextureFactory, CityIconRenderer, PortMarkerRenderer)",
      "Ship classes documentation: 9 types with tonnage, draft, reef mechanics",
      "14 zoom levels (1.5x-12x), ship sprite scales with zoom",
    ],
  },
  {
    version: "0.8.6",
    date: "2026-03-19",
    changes: [
      "14 zoom levels (0.5x–20.0x) — z13 Spyglass, z14 Crow's Nest",
      "City icons: atmospheric pixel art (colonial buildings, palm trees, thatched huts)",
      "3 city sizes visually distinct: large (walled town), medium (colonial), small (village)",
      "City labels: white text with shadow, sqrt-zoom scaling, always readable",
      "City labels positioned below cities, depth 600 (never obscured)",
      "11 port positions corrected to match real Caribbean geography",
      "Tortuga fixed: separate island from Hispaniola (land grid 4x4 sub-sampling)",
      "Port approach radius reduced 40% — must sail closer to trigger dialog",
      "Fort icons: stone walls with corner towers, battlements, cannon positions",
      "Small cities: no more dock/pier artifact, palm trees instead",
    ],
  },
  {
    version: "0.8.5",
    date: "2026-03-19",
    changes: [
      "10 zoom levels (0.5x–8.0x), default z8 (5.0x)",
      "Clouds: smaller (50%), more numerous, spread across entire map, fade-in",
      "Seagulls: 2 sizes, soft coastal steering, only over water near coast",
      "Ship sprite 30% smaller for better map proportion",
      "Date moved to UIOverlay (top-right, no time), zoom-independent",
      "Port departure fix: ship pushed perpendicular to coast toward open sea",
      "Cloud height variety: flat/medium/tall cumulus profiles",
      "Wind displayed in knots on compass",
    ],
  },
  {
    version: "0.8.4.1",
    date: "2026-03-19",
    changes: [
      "NPC ships: spawn from ports, port-to-port AI, fog-of-war (V toggle)",
      "UIOverlayScene: wind compass + version label (zoom-independent)",
      "Clean UI: minimap removed, HUD moved to SPACE menu",
      "Start with furled sails on new/loaded game",
      "Embark fix: perpendicular-to-coast departure with grace period",
      "Comprehensive documentation (11 docs) + AI assets subproject",
    ],
  },
  {
    version: "0.8.4",
    date: "2026-02-20",
    changes: [
      "Classic map: caribbean_bg.png background (GitHub v0.8.2 style)",
      "Generated pack: procedural blob tiles + water_tile overlay",
      "Asset pack now controls map rendering style",
      "Dancing Script font (local, full Polish support)",
      "All fonts scaled +30% for readability",
      "Nationality-specific starting cities",
      "Renamed menu tabs (shorter labels)",
      "Options dialog enlarged 20%",
      "Puppeteer screenshot tool",
    ],
  },
  {
    version: "0.8.3",
    date: "2026-02-20",
    changes: [
      "Two-step character creation: name/era + nationality/skills",
      "Captain profile: 5 skills (fencing, gunnery, navigation, medicine, charm)",
      "Skill point allocation with 10 bonus points",
      "Ship faction now matches captain's nationality",
      "+20 reputation bonus with own nation at game start",
      "New 'Captain' tab in options menu (skills, ranks, age)",
      "Save migration v5: old saves get default captain profile",
      "Changelog visible in-game (Quartermaster tab)",
      "Allura italic font (replaces Treasure Map Deadhand, Polish support)",
      "New start screen music (pirate_adventure.wav)",
    ],
  },
  {
    version: "0.8.2",
    date: "2026-02-19",
    changes: [
      "Version label in bottom-right corner (start screen)",
      "Larger version font (8px -> 12px)",
      "Beach fringe overlay fix",
    ],
  },
  {
    version: "0.8.1",
    date: "2026-02-19",
    changes: [
      "Custom pirate font (Treasure Map Deadhand)",
      "Wind rose compass on map",
      "Caribbean map in options menu",
      "Smaller, cleaner dialog panels",
      "45 cities with full port data",
      "Shipyard: buy ships, repair hull",
      "Tavern: recruit crew, buy drinks, hear rumors",
      "Governor: ranks, letters of marque",
      "Era selection (6 historical eras)",
      "Save/load system (5 slots)",
      "Event log and calendar",
      "Asset pack switching (classic / AI sprites)",
      "Zoom level setting (far / normal / close)",
      "Polish language support",
    ],
  },
  {
    version: "0.8.0",
    date: "2026-02-18",
    changes: [
      "Initial release: Caribbean sailing, trading, combat",
      "Procedural world generation with factions",
      "Sea battle system",
      "Port trading and docking",
    ],
  },
];
