export type ChangelogEntry = {
  version: string;
  date: string;
  changes: string[];
};

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "0.37.0.0",
    date: "2026-09-05",
    changes: [
      "THE COMMISSION IS A JOB",
      "  A LETTER OF MARQUE HAS BEEN A KEEPSAKE since the first governor's",
      "  dialogue. Two systems read it — you count as an ally when a crown",
      "  retakes a town, and you may hand a captured town to a patron — and",
      "  that was all. At sea the paper did nothing whatever",
      "  A PRIZE TAKEN FROM AN ENEMY OF YOUR PATRON is now declared good. The",
      "  crown thinks better of you for it, and the brethren credit you with",
      "  only half of what they would: a privateer is not a pirate",
      "  A PRIZE TAKEN FROM SOMEBODY HE IS AT PEACE WITH embarrasses him, and",
      "  it costs more than a covered prize pays. That is what carrying the",
      "  paper is worth — without one, an indiscriminate captain answers to",
      "  nobody at all",
      "  TURN ON YOUR PATRON and the letter is torn up on the spot. Nothing",
      "  else in the game revokes a commission, and nothing else should",
      "  ONE CROWN AT A TIME. You could collect all four letters and be covered",
      "  against everybody by somebody, which made 'which crown do I serve' a",
      "  question with no answer. Signing a new commission gives up the old",
      "  one, and the governor says so before you sign",
      "  The Journal has been printing 'england' where it meant England since",
      "  the letter was first handed over. Fixed",
      "  `?marque=<port>` stands you at a governor's desk with another crown's",
      "  paper already in your coat",
    ],
  },
  {
    version: "0.36.0.0",
    date: "2026-09-05",
    changes: [
      "THE SEA KNOWS YOUR NAME",
      "  EVERY MERCHANT RUNS FROM YOU NOW, not only the six with names.",
      "  v0.35.0 taught the named hulls to run; the rest of the Caribbean went",
      "  on steering at its destination while a black flag came down on it, as",
      "  though nobody had heard of you",
      "  NOTHING CHANGES FOR AN HONEST CAPTAIN. It is the same test the navy",
      "  and the named ships already use: a black flag, a crown that has come",
      "  to hate you, or a notoriety past 50. Below that, traders sail up to",
      "  you exactly as they always have",
      "  WHICH MAKES NOTORIETY COST SOMETHING AT LAST. Until now a great name",
      "  bought you extra patrols and better smuggling; now it also means the",
      "  merchant service will not stand still to be collected",
      "  She runs AWAY from you rather than towards anywhere — she has no",
      "  schedule to keep and her hold is owed to one particular warehouse, so",
      "  her destination is never changed. Let her go and she picks the voyage",
      "  up where she left it",
      "  And she runs on the best point of sail she has, off the same polar",
      "  curve your own ship uses. A laden fluyt is still a laden fluyt: work",
      "  the wind and you will have her",
      "  `?skip&notoriety=N` gives a captain a name before he has earned one",
    ],
  },
  {
    version: "0.35.0.0",
    date: "2026-09-05",
    changes: [
      "SHE RUNS",
      "  A NAMED SHIP MET AT SEA NO LONGER STANDS ON. v0.34.0 gave her an",
      "  answer she could only give in harbour; run her down on the water and",
      "  she still sailed her course straight at you, because a merchantman is",
      "  a trader hull and a trader steers at its destination",
      "  Now she bolts for one of the two ends of her own passage — whichever",
      "  she has the better head start to — under everything she has",
      "  WHICH END IS THE WHOLE MECHANIC. Put your ship between her and the",
      "  near harbour and she is forced onto the long passage; leave the gap",
      "  and she takes it. That is a decision you make with your helm, not a",
      "  die roll, and both ends are on her lane so a chase never puts her",
      "  chart position out of step with her",
      "  THE CHASE IS A WIND PROBLEM. She does not point at the harbour, she",
      "  picks the heading with the best speed MADE GOOD toward it, off the",
      "  same polar curve your own ship sails by. A square rig with a sixty-",
      "  degree dead zone running for a harbour dead upwind will go wide, and",
      "  a fore-and-aft rig that can point higher is what catches her",
      "  HER ESCORTS TURN BACK. The moment she runs, the convoy comes about",
      "  and closes on you whatever your standing with her crown — that is",
      "  what a convoy is for. Fight through it and she gains the whole time",
      "  UNDER THE GUNS OF THE HARBOUR she is gone: stamped as having made",
      "  that port, kept in for two days, off the chart. You are told she got",
      "  in, and your reckoning is wrong from that morning on",
      "  Being chased is deliberately not a scare. A fight teaches her",
      "  something; a chase she won taught her nothing, and escalating on it",
      "  would let a captain who never lands a shot drive her convoy up",
      "  She runs from a black flag and from a crown that hates you always,",
      "  and from ANYBODY once somebody has put a shot into her. The first",
      "  interception is clean. Every one after it has to be earned",
    ],
  },
  {
    version: "0.34.0.0",
    date: "2026-09-05",
    changes: [
      "SHE FINDS OUT",
      "  A NAMED SHIP REMEMBERS THE FIGHT SHE LIVED THROUGH. Until now she",
      "  worked her run whatever happened to her: break off an attack and you",
      "  would find her a week later exactly where the chart said, which made",
      "  your reckoning a tracker that nothing in the world could contradict",
      "  Now an engagement she survives is an unanswered scare, and she answers",
      "  it in harbour, where you cannot see her do it",
      "  SHE SAILS LATE. Two days alongside for every scare she is carrying, up",
      "  to six. Sit exactly where your arithmetic puts her and you sit on",
      "  empty water, because she has not left yet",
      "  SHE TAKES ON A CONSORT. Up to the same two the galleon has always had:",
      "  a fluyt you jumped once is no longer the easy one. A galleon already",
      "  at the ceiling answers with her sailing date and her route instead",
      "  SHE CHANGES HER RUN. From the second scare, her house works her out of",
      "  that harbour on a different lane altogether — and your chart goes on",
      "  drawing the course you were told about, with a mark walking along it",
      "  that is nowhere near her",
      "  Two scares means you pressed her: fought her escort and then her, or",
      "  came back for a second attempt. One exchange of fire does not buy it",
      "  THE TAVERN IS THE WAY BACK. A town within earshot will tell you she is",
      "  still lying at Barbados and that somebody put a shot into her, and",
      "  reading that redraws her run on your chart from scratch. Seeing her",
      "  yourself does the same. Your information is exactly as good as the",
      "  last thing you were told — which is the whole point of the hunt",
      "  Every new field is optional, so a v0.33.0 save reads as a Caribbean",
      "  nobody has been hunting in and migrations stay at v12",
    ],
  },
  {
    version: "0.33.0.0",
    date: "2026-09-05",
    changes: [
      "THE HUNT IS A CHART PROBLEM AND A FIGHT",
      "  WHERE YOU WERE TOLD SHE WOULD BE. A named merchantman you have heard",
      "  of now has her run drawn on the chart, and one mark where your own",
      "  reckoning puts her — the phase she was at when somebody told you,",
      "  walked forward by the days since",
      "  It is not her position and it never will be. A marker that followed",
      "  her would turn an interception into following an arrow, and the whole",
      "  content of the commission is the guess about which end of the passage",
      "  to sit on. The mark is right until something interferes with her",
      "  Three ways to get a report, and they are the three a captain would:",
      "  signing the commission (the informer knows her book), a tavern within",
      "  earshot saying she has just cleared a harbour, and seeing her yourself",
      "  The mark fades and is gone after three weeks. Her circuit is a",
      "  fortnight, so an older report puts her anywhere on the run with equal",
      "  probability and a confident arrow would be the chart lying to you",
      "  SHE IS NOT ALONE ANY MORE. The richest of them sail in company: a",
      "  galleon with two escorts, a merchantman with one, a fluyt with none.",
      "  Warships on convoy duty, and they close on whoever closes on her",
      "  The commission pays half again for every hull with her, because that",
      "  is what the house is really paying to get past",
      "  Sink an escort and break off and it stays sunk — the convoy is counted",
      "  from what is still afloat, never from what somebody subtracted",
      "  A save from v0.32.0 reads her as sailing alone, and grows no convoy",
    ],
  },
  {
    version: "0.32.0.0",
    date: "2026-09-05",
    changes: [
      "A SHIP WITH A NAME",
      "  Every hull in this game was anonymous: spawned inside your horizon,",
      "  forgotten behind you, and two fluyts off Havana on consecutive",
      "  mornings were never the same fluyt. Six merchantmen are not, now.",
      "  They have names, crowns, classes and a run they work back and forth",
      "  on a schedule, and they are the same ship next week",
      "  She is bookkeeping while you are elsewhere and a real hull when you",
      "  are near, and what you do to her sticks: shoot her rigging away and",
      "  break off, and she is still short a topmast when you find her again",
      "  THE INFORMER'S THIRD COMMISSION, listed as waiting since v0.25.0 and",
      "  impossible until now. Cutting a lane is a statistical job — be there a",
      "  fortnight and take enough hulls. This is one ship, by name, and the",
      "  whole problem is interception: she cleared Florida Keys six days ago",
      "  and makes the passage in nine, so where should you be tomorrow",
      "  Sunk or struck, the house is not particular. Taking her is worth more",
      "  to you than sinking her and exactly the same to them",
      "  Her crown remembers it harder than a lane raid — a lane is an",
      "  inconvenience, a named ship is somebody's ruin",
      "  The tavern will tell you when one of them has just cleared a harbour",
      "  within earshot. It is the only way to learn which end of the run she",
      "  is on, and it goes stale after three days",
      "  The tavern list can carry ten entries now, so the keyboard hint stands",
      "  down when the informer has all three of his jobs on the table",
      "  Debug: ?hunt=<port> for the tavern, &meet=1 to be put alongside her",
    ],
  },
  {
    version: "0.31.0.0",
    date: "2026-09-05",
    changes: [
      "THE WARS YOU WERE BORN INTO",
      "  A historical war was only ever created on the exact day its start date",
      "  came round, which is right for a war that breaks out during a career",
      "  and wrong for the day the career begins. Three of the six eras open",
      "  inside a war — 1600 inside two, 1620 inside the Eighty Years' War,",
      "  1640 inside two — and every one of them opened in perfect peace, with",
      "  the fighting mentioned only in the past tense",
      "  They are on the map now. The tavern says how long it has been going on",
      "  rather than announcing a fifty-two-year-old war as fresh news, the navy",
      "  of both crowns is out in double strength, and privateers are at sea",
      "  A WAR HURTS TRADE WORST WHEN IT BREAKS OUT. Seeding those wars with a",
      "  flat penalty took 39% off the wealth of the entire Caribbean and held",
      "  it there for decades — an eighty-year perturbation is not a",
      "  perturbation, it is the setting. So the bite fades over two years as",
      "  neutral bottoms are chartered and new routes settle",
      "  You will feel this in play: the Nine Years' War now costs English",
      "  colonies about a third of their wealth in the first months and lets",
      "  them recover while the fighting goes on, instead of holding both crowns",
      "  at half their worth for eight straight years",
      "  Removed the pause menu — 112 lines of scene that nothing has been able",
      "  to open since the first commit; SPACE has done the job for months",
      "  Fixed: the Polish governor no longer forgets which crown he serves when",
      "  he hands over a letter of marque",
      "  Debug: ?era=<id> with ?skip to start in any of the six historical eras",
    ],
  },
  {
    version: "0.30.0.0",
    date: "2026-09-05",
    changes: [
      "THE CHART SAYS WHAT IS HAPPENING, AND PEACE HAPPENS AT ALL",
      "  MARKS ON THE MAP. v0.28.0 made world events land on towns and v0.29.0",
      "  gave you things to do about them, and between the two the map itself",
      "  said nothing: forty-five identical towns whatever was going on in",
      "  them. A town you have heard something about now carries a pin and the",
      "  name of the thing — rust for trouble, gold for an opportunity — and a",
      "  harbour that is shut gets a broken ring you can read from a mile off",
      "  Only what you have been told. The marks come from the same set as the",
      "  expedition courses: a tavern noticeboard or a captain you hailed. A",
      "  crown-wide decree is not marked, because it is news about a flag and",
      "  twenty-four identical pins would bury the one hurricane that matters",
      "  N hides them, the way T hides the trade lanes",
      "  PEACE. Every historical war stored its end as years times 365, against",
      "  a calendar that keeps leap days — so each one quietly evaporated a few",
      "  days before its own end date, the end-of-war branch never ran, and the",
      "  treaty it was supposed to sign has never once existed. The peace is an",
      "  event now: sixty days of reopened routes across both crowns, on the",
      "  news boards of every town in them, and the effects table row that had",
      "  sat unused since v0.9.7 finally does something",
      "  Debug: ?zoom= took effect on the next load of the page rather than",
      "  this one, so anything driving the game headless was silently looking",
      "  at the stored zoom instead of the one it asked for",
    ],
  },
  {
    version: "0.29.0.0",
    date: "2026-09-04",
    changes: [
      "THE EVENTS ARE SOMETHING YOU MEET NOW",
      "  v0.28.0 discovered that no world event had ever attached itself to a",
      "  town. With them finally landing, three of the things they claim to do",
      "  turned out to be claims: nothing in the game read them",
      "  A SHUT HARBOUR IS SHUT. A hurricane or a quarantine closed a port for",
      "  the daily economy and for nobody else — you sailed in and traded",
      "  across a counter nobody was standing behind. Now the approach says so",
      "  and the door is not offered. Storming the town still is: a closed",
      "  harbour is a weak harbour, and that is a decision rather than a bug",
      "  A PLAGUE EMPTIES THE TAVERN. Every event has carried a recruiting",
      "  multiplier since the system was written and nothing had ever read it.",
      "  An epidemic now halves the men who will sign, a famine takes a third",
      "  — on top of what the town thinks of you and how hungry it is",
      "  A GOLD STRIKE IS WORTH SAILING TO. Gold has been produced by boom",
      "  towns since v0.9.7 and was not a tradeable item, so the merchant never",
      "  listed it and the counter refused it as unknown goods. It is a good",
      "  now — a rare one: no port holds a grain of it, and it appears on a",
      "  counter only where it has been struck, or in your own hold",
      "  Buy it where they dig it and it is cheap; anywhere else has none and",
      "  quotes accordingly. A boom town is finally a place on the chart worth",
      "  a passage",
      "  And the tavern will tell you a harbour is shut before you waste the",
      "  voyage — the one fact you cannot go and read for yourself, because the",
      "  news board is behind the door you are being refused at",
    ],
  },
  {
    version: "0.28.0.0",
    date: "2026-09-04",
    changes: [
      "THE EVENTS WERE NEVER HAPPENING",
      "  One line, wrong since the module was written: the port for a world",
      "  event was picked with `ports[roll % ports.length]`, and the roll is a",
      "  fraction between 0 and 1. Every event the game ever created looked up",
      "  `ports[0.37]` and got nothing",
      "  So the headlines read 'a treasure fleet preparing to sail from",
      "  undefined', every event belonged to the pirates, no tavern in the",
      "  Caribbean carried the news, and — the half nobody could see — not one",
      "  of the fifteen event types ever touched the town it was about. Fires,",
      "  plagues, gold strikes and royal decrees, all of them decoration",
      "  Found by reading a noticeboard in a screenshot",
      "  Events now land on real towns, and the table they run on has been",
      "  measured for the first time: a day of standing pressure is worth a",
      "  hundred points of a town's wealth, so a gold strike at +10 a day was",
      "  the entire scale. Rescaled to a rule — an event perturbs a town, it",
      "  does not re-found it — and a year of them now moves the Caribbean's",
      "  total wealth by a few percent instead of by 39%",
      "  And one of a kind per town: a crown does not issue three tariff",
      "  decrees at once, which is what used to pin every rich Spanish colony",
      "  to the top of the scale",
      "WHAT THEY ARE SAYING IN THE TAVERN",
      "  The rumour was eight strings rotated by the day of the month — the",
      "  same ghost ship off Bermuda whether you had spent the month",
      "  blockading Havana or asleep",
      "  Now the tavern reports the world: a town within earshot that cannot",
      "  feed itself and what it is short of, a squadron lying off a harbour, a",
      "  quay carrying somebody else's runs, a lane no underwriter will touch,",
      "  a town flying no crown's colours, the busiest quay in reach",
      "  Gossip is local. Only what is happening within earshot is on offer, so",
      "  the tavern in a busy hub is a better place to drink than the one in a",
      "  back bay — and buying a round is finally a way of finding out where to",
      "  sail with a hold of food",
      "  One thing a day, rotating: come back tomorrow and hear the next fact",
      "  rather than the same one. The old stories still get told when the",
      "  Caribbean has little else to say",
    ],
  },
  {
    version: "0.27.0.0",
    date: "2026-09-04",
    changes: [
      "A HUNGRY TOWN LOOKS HUNGRY",
      "  A shortage has cost a town money since v0.20.0 and nothing else.",
      "  Nobody left, no screen said so, and the tavern was as full in a famine",
      "  as in a good year — so the thing you can now cause on purpose (a",
      "  blockade, a conquest, a lane cut until the second source runs dry) was",
      "  invisible from inside the town it happened to",
      "  Every port now records what share of its needs went unmet yesterday.",
      "  The port menu says so on the way in: 'Short commons: the town went",
      "  without 45% of what it needed'",
      "  People leave. A town that never eats settles at about seven-tenths of",
      "  its people; one going half short at five-sixths. It thins, it does not",
      "  empty — and a fed Caribbean is exactly where it was, to the head",
      "  Men sign for a berth and a meal: a starving town puts up to twice as",
      "  many hands on the tavern bench. The shortage you can cause is a",
      "  shortage you can crew out of",
      "THE PUBLIC GRANARY",
      "  The governor of a hungry town will buy what is in your hold, on the",
      "  spot — no contract, no deadline, nothing to sign",
      "  He pays the crown's price in gold and the rest in standing: up to 8",
      "  points of reputation for filling the shed, whatever he thought of you",
      "  when you walked in. Starve a colony by taking its supplier, then sail",
      "  back with the answer and buy your way into its good books",
      "  He asks for the good the town has fewest days of, and never bids above",
      "  what his own merchant is charging for it — a crown relieving its own",
      "  colony is not bidding against itself",
      "  Landing the cargo closes the gap, so he cannot be sold to twice in an",
      "  afternoon. The shelf has to empty again first",
    ],
  },
  {
    version: "0.26.0.0",
    date: "2026-09-04",
    changes: [
      "A CARGO NOW LEAVES SOMEBODY'S WAREHOUSE",
      "  Lanes have delivered goods since v0.22.0 and paid for them since",
      "  v0.24.0, but nothing anywhere went down by a barrel: the cargo was",
      "  conjured at the far end. So a town that suddenly took over a",
      "  blockaded rival's runs was neither strained nor enriched by it",
      "  Now a delivery is drawn out of the exporter's sheds. In a quiet",
      "  Caribbean nothing changes at all — a plantation grows what its own",
      "  lanes carry, and the measured wealth of every town is where v0.25.0",
      "  left it, to the decimal",
      "  Take a town, or shut a harbour, and its customers go to the next",
      "  grower along — who never planted for them. His warehouse empties in",
      "  a week, his prices go to the ceiling, and his own coffers fill: the",
      "  strain and the windfall are the same fact",
      "  When his sheds run dry the orders are short-shipped pro rata, and",
      "  every town he was covering for goes hungry too. A second source is a",
      "  finite second source, so a conquest is felt across the sea for far",
      "  longer than the fortnight the neighbours' warehouses last",
      "  A producer works harder for an empty shed than a full one — up to",
      "  double his ordinary output — so a port the player has bought out",
      "  restocks in days rather than in a month",
      "  The merchant's counter says why the shelves are bare: 'Covering",
      "  another port's runs: Food 23.7 t/d'",
      "THE INFORMER'S OTHER LINE OF WORK",
      "  A relief order: land so many tons of a good in a town that cannot",
      "  get it, inside 24 days, for a price agreed in advance",
      "  It is not a charter. The house hands over nothing — where the goods",
      "  come from is the captain's affair, and a hold taken out of a prize",
      "  counts as well as one bought at a plantation",
      "  What is being paid for is a fixed price for the whole hold. Selling",
      "  forty tons over the counter of a hungry town slides the quote down",
      "  under your own feet; this does not. And the rate is always struck",
      "  below what that town's own merchant is asking, or the job would be",
      "  to buy at the counter and sell it back across the same table",
      "  Landing it pays gold, +3 notoriety and +6 reputation with the crown",
      "  you fed — the exact opposite of the raiding commission, which is the",
      "  point of the informer having both",
    ],
  },
  {
    version: "0.25.0.0",
    date: "2026-09-04",
    changes: [
      "YOU CAN SEE WHICH MERCHANTMAN IS WORTH CHASING",
      "  Since v0.23.0 traders have carried real cargo out of real warehouses,",
      "  and some of them sail in ballast because the quay was bare. Nothing on",
      "  the map ever said which was which, so running one down was a coin toss",
      "  that cost a day of fair wind",
      "  A gold burgee now flies under the ensign of anything with goods in",
      "  her. Short pennant = a part cargo (10% of her hold or more), long",
      "  bright pennant = deep-laden (half her hold or more), nothing = in",
      "  ballast",
      "  It only shows inside 55% of your lookout's range: at the edge of",
      "  vision a hull is a sail and nothing more. Closing to read her is a",
      "  decision, and the tallest mast in your fleet is now worth something",
      "  twice over",
      "  The encounter screen names the cargo outright — 'Laden: 80 tons —",
      "  Sugar Cane', in the order a prize crew would shift it",
      "THE INFORMER AT THE BACK OF THE TAVERN",
      "  A third source of work, and the first that is not the crown's. The",
      "  governor commissions a defence, the freight office a passage; the",
      "  informer sells somebody else's trade, ruined to order",
      "  A merchant house pays 250-1150 gold to make a named shipping lane",
      "  uninsurable. Take her merchantmen on that run: three hulls inside a",
      "  fortnight will do it, two will not, because the shippers' nerve comes",
      "  back 12% a day and a captain who dawdles watches his own work decay",
      "  One commission at a time, 30 days, and never against the town's own",
      "  crown. Paid the day the lane goes quiet: gold, +8 notoriety, and -14",
      "  reputation with the crown whose trade it was",
      "A TOWN UNDER THE BLACK FLAG IS NOT A COLONY",
      "  No licensed merchant will lade at a pirate den, so a town you hold is",
      "  cut out of the lane network as a supplier. Every colony that bought",
      "  from it now goes to the next grower along or goes short — taking",
      "  Havana is felt in four towns you have never visited",
      "  And the ledger pays whoever actually shipped the cargo. Before this a",
      "  blockaded or captured port went on being credited for goods it plainly",
      "  had not sent",
      "  Your own den lives on smuggling, and smugglers sail to a name. Its",
      "  imports rise from 35% to 75% of what a colony gets as your notoriety",
      "  climbs to 100 — settling a captured Port Royale anywhere between 223",
      "  and 465 wealth. It is the first thing notoriety has ever been worth",
      "  rather than merely cost",
      "  Deliberately NOT changed: a held town's wealth still drifts toward the",
      "  royal baseline. Measured twice this release — a lower target and a",
      "  daily upkeep each emptied the town to zero inside a year, because the",
      "  standing shortage already eats the whole gap. A ceiling is not an",
      "  equilibrium",
      "No save migration: the chain stays at v12. Nothing new is stored — the",
      "  commission lives in the quest log like every other contract",
    ],
  },
  {
    version: "0.24.0.0",
    date: "2026-09-04",
    changes: [
      "TRADE HAS MONEY IN IT NOW, AND TOWNS HAVE OPINIONS",
      "  Last release made the goods physically travel. Nobody paid for any of",
      "  them. A town at the hub of six shipping lanes was worth exactly as",
      "  much as an identical town at the end of none",
      "  Wherever goods move, money now moves with them. A lane delivery pays",
      "  the exporter for his cargo and lets the importer's merchants keep part",
      "  of what they make reselling it — both ends gain, because that is the",
      "  entire reason trade exists: a barrel of cocoa is worth more where",
      "  nobody grows it",
      "  So cutting a lane costs both towns money. A blockade, a season of",
      "  commerce raiding, a war — all of them show up in the books now, and",
      "  the approach screen tells you what a town's quay is worth per day. It",
      "  is the number that moves when your campaign is working",
      "PRICES MOVE WHILE YOU STAND AT THE COUNTER",
      "  Quotes used to be worked out once a night. Two hundred tons of sugar",
      "  sold into a fishing village all went at the price of the first ton, so",
      "  the whole trading game was find the biggest spread and repeat",
      "  Now every hand that touches a warehouse requotes it — your buying and",
      "  selling, a trader loading out, a convoy landing her hold. Buy a",
      "  warehouse out and watch the price climb under your hand. A convoy",
      "  making port moves the market the moment she ties up",
      "  And your gold is the town's gold. What you pay over the counter goes",
      "  into the place; what it pays you comes out of it. Dump a hold on a",
      "  small town and it is measurably poorer for it",
      "EVERY CROWN'S OPINION OF YOU FINALLY REACHES THE QUAY",
      "  Eleven releases recorded what each crown thought of you, and then let",
      "  you walk past the fort and be served exactly like everybody else.",
      "  Cartagena, which you had spent a year burning, sold you powder at Port",
      "  Royale's price and let its sons ship out with you",
      "  THE MERCHANT deals with anyone, at a price — but the gap between what",
      "  he asks and what he offers is his opinion of you. An ally quotes",
      "  within a few percent; a town you have been burning takes thirty either",
      "  way and makes its feelings back on every barrel",
      "  THE TAVERN is where it bites hardest. Men sign on with a captain their",
      "  families do not hate. In a hostile town, nobody will",
      "  THE FREIGHT OFFICE has no work for a man his own crown has a price on.",
      "  Nor will any landlord lease him a building",
      "  THE YARD will mend anybody's hull — a shipwright is not a patriot —",
      "  but it charges an enemy double, and it will not sell him a ship",
      "A WAREHOUSE OF YOUR OWN, IN ANY TOWN THAT WILL LEASE YOU ONE",
      "  Until now there was exactly one place to put cargo down: the family",
      "  storehouse your marriage gave you, in one town. Everywhere else your",
      "  hold was your whole fortune",
      "  Rent a shed on the quay for a month and the goods can wait — for a",
      "  better price, for a bigger ship, for the war to end. A hundred tons in",
      "  an outpost, five hundred in a capital",
      "  The rent runs whether you are there or not. Let it lapse and the",
      "  landlord auctions what is inside and sends on half of what it fetched",
      "  What is stored is yours, not the town's: it does not feed the place and",
      "  it does not move its prices until you sell it",
      "FIXED",
      "  A friendly town would ask 14 for sugar and offer 16 — you could stand",
      "  at the counter buying and selling the same barrel until you owned the",
      "  Caribbean. The merchant now quotes a bid and an ask around one price,",
      "  which cannot do that however you are regarded",
      "  Port wealth is kept to a tenth of a point. A day's honest trade through",
      "  a busy quay is worth about half a point, and rounding the total to a",
      "  whole number every midnight threw it away — the ledger balanced four",
      "  points above baseline instead of the fifty the arithmetic says",
    ],
  },
  {
    version: "0.23.0.0",
    date: "2026-09-04",
    changes: [
      "YOU CAN BE PAID TO SAIL THE LANES NOW, NOT ONLY TO CUT THEM",
      "  Last release gave the Caribbean real shipping and three ways to attack",
      "  it. It left you standing on the quay watching it go past",
      "  Every port with a lane out of it now has a FREIGHT OFFICE: a merchant",
      "  with cargo and no bottom to put it in pays for a passage. Carry so much",
      "  of this to that town by that day and the money is waiting",
      "  The fee is what the run is actually worth today. Long passages pay. A",
      "  lane that has been losing hulls to pirates lately pays DANGER MONEY,",
      "  because nobody else will take it — so the captain who spent last month",
      "  sinking merchantmen on the Havana run is offered more to sail it",
      "  himself. A blockaded destination pays most of all: getting in is the job",
      "  And the cargo is not yours. Sell it in the wrong port and nothing stops",
      "  you — the charter lapses, the crown that paid for it takes it",
      "  personally, and your notoriety goes up. The honest carrier and the",
      "  thief use the same screen",
      "THE GOODS THEMSELVES ACTUALLY MOVE",
      "  A trader leaving port now loads out of that port's warehouse, and one",
      "  arriving lands her hold into the warehouse at the far end. Goods leave",
      "  one place and reach another instead of being conjured at the hatch",
      "  A hull may draw a warehouse down but never strip it: the ships near you",
      "  are a sample of the trade, not the whole of it",
      "  So a convoy you take is a delivery that never arrives, in goods, not",
      "  only in an abstract ledger",
      "A BLOCKADE IS ONLY AS GOOD AS THE PORT IT SHUTS",
      "  Until now, shutting a harbour cut its customers to a third whether or",
      "  not somebody else grew the same thing a day further on",
      "  The trade now goes the long way round when it can — worse, slower, but",
      "  not a famine. Blockading the ONLY cocoa port in reach is devastating;",
      "  blockading one of four sugar ports is an inconvenience. Choosing which",
      "  harbour to sit on is finally a decision",
      "THE INVASION SAILS ROUND THE HEADLAND",
      "  A crown's expedition walked a ruled line from its harbour to its target,",
      "  which sometimes ran straight through a peninsula and put the squadron",
      "  ashore on the reckoning. It follows the real water now, and the dashed",
      "  course on the chart is the course it actually takes",
    ],
  },
  {
    version: "0.22.0.0",
    date: "2026-09-04",
    changes: [
      "THE SEA HAS SHIPPING ON IT NOW, AND YOU CAN CUT IT",
      "  Trade between ports was a number: every colony was topped up with what",
      "  it could not grow, from nowhere in particular, by nobody. A war took a",
      "  flat third off it whether the town sat on a strait or in a back bay",
      "  Every good a town needs and cannot grow now has a named supplier and a",
      "  real course between the two, worked out round the islands rather than",
      "  ruled through them. Press T to see the lanes on the chart",
      "  Water is the exception and always will be: nobody ships it, it comes",
      "  out of a well. A blockade starves a town of food and rum, not of thirst",
      "SEA PATHFINDING — the empty hook is finally a road",
      "  `Pathfinding.ts` had been a placeholder returning null since the first",
      "  commit. It is now an A* over the sea, and traders follow the course it",
      "  gives them corner by corner instead of steering at the harbour and",
      "  bouncing off whatever headland was in the way",
      "BLOCKADE — the first thing you can do to a town without landing on it",
      "  Lie off a harbour you do not hold, with guns enough to matter against",
      "  its batteries, and the cordon tightens a day at a time. After two days",
      "  it bites: the lanes into that port carry a seventh of what they did,",
      "  its wealth bleeds, and its garrison stops being paid and starts thinning",
      "  The crown that owns it does not forget — your standing falls every day",
      "  you sit there, your notoriety rises, and its navy fits out for that",
      "  harbour. Sail off and the cordon slackens a day at a time, so watering",
      "  ship does not undo a fortnight's work",
      "  A starved town is a takeable town. This is the slow half of the siege",
      "A PRIZE NOW HAS A HOLD",
      "  Beating a ship paid a random 50-150 gold whether she was a plate-fleet",
      "  galleon or a fishing pinnace, and her hold was always empty",
      "  Traders now load from the lane they are sailing, so a merchantman on",
      "  the Havana run is carrying sugar and rum. Take her and the cargo comes",
      "  across — as much of it as your own hold will take, and the screen tells",
      "  you what you had to leave in the water",
      "  The purse is her tonnage broken up, not a die roll: a big prize pays",
      "  like one even when her hold was empty. She struck? You save more. She",
      "  went down under you? Half of it goes with her",
      "  And preying on a lane thins it: the town at the far end feels it within",
      "  the week, and the chart draws that lane in a warmer colour",
    ],
  },
  {
    version: "0.21.0.0",
    date: "2026-09-04",
    changes: [
      "A WAR IS NOW SOMETHING EVERY PORT FEELS",
      "  Ten historical wars have been on the news board since v0.9.7. They",
      "  doubled patrols, moved prices a little and — since v0.16.0 — moved",
      "  flags. What they never did was reach the quay",
      "  Events now carry a shipping term of their own, separate from what they",
      "  do to the harvest: a war takes a third off what reaches a port of either",
      "  crown, a pirate raid a quarter, and a treaty gives it back",
      "  A colony that spends years at war is measurably poorer for it, and it",
      "  recovers when the war ends. Felt, not fatal",
      "CONSORT CREWS ARE GREEN — a second ship is a decision, not free guns",
      "  A hull that joins your fleet is manned by a prize crew or a yard's",
      "  delivery crew, not by people you have spent years drilling. It starts a",
      "  notch below your own and catches up while it sails in company",
      "  It reloads at its own drill in a sea battle, and a siege bombardment",
      "  pools drill across the fleet weighted by men — so buying a galleon on",
      "  Tuesday makes you worse at storming a fort on Wednesday, and better at",
      "  it by the spring",
      "  The Cabin tab shows each consort's crew, morale and drill",
    ],
  },
  {
    version: "0.20.0.0",
    date: "2026-09-04",
    changes: [
      "EVERY PORT IN THE GAME WAS QUIETLY STARVING",
      "  A town consumed the goods it demands out of its own inventory, and",
      "  nothing ever put them there. There is no inter-port trade simulation, so",
      "  every good a town needed but did not produce was short every single day,",
      "  for ever, and cost it a flat point of wealth for the failure",
      "  Port Royale demands sugar, cocoa and tobacco and produces neither. It",
      "  bled three wealth a day from the moment the world was made and settled",
      "  at 353 against a baseline of 600 — as did every other port, in its own",
      "  proportion. The baselines were a fiction nothing could reach",
      "  Licensed trade now brings a colony what it needs. A port at peace under",
      "  a crown settles exactly at its baseline, which is what a baseline was",
      "  always supposed to mean",
      "  Loot on day one is unchanged. What changes is that towns no longer",
      "  wither: a Cartagena you come back to in five years is the Cartagena you",
      "  left, not a shadow of it",
      "  And the black flag now costs a town its imports rather than a modifier",
      "  on its books — no merchant will call, smugglers bring a third of what a",
      "  packet would, and the shortage does the rest. One mechanism instead of",
      "  two, and the wealth cap added in v0.19.0 is gone",
      "A WAR PENNANT — the ensign says whose, this says what",
      "  Every hull on the map is drawn from one sprite sheet, so a merchantman",
      "  and a frigate of the same crown were indistinguishable until you were",
      "  close enough to hail — by which time the frigate has decided what it",
      "  thinks of you",
      "  Navy, pirates and pirate hunters now fly a red streamer above the",
      "  ensign. Traders do not",
    ],
  },
  {
    version: "0.19.0.0",
    date: "2026-09-03",
    changes: [
      "WHOSE SHIP IS THAT — every NPC hull now flies its colours",
      "  The most useful thing on the map was also the hardest to find out: you",
      "  had to sail up to a strange sail and open the encounter dialogue to",
      "  learn whose it was",
      "  A small ensign beside each hull, the same flags the ports fly. It",
      "  follows the hull's own fade, so fog never gives itself away by leaving",
      "  a flag hanging in empty water, and it is a fixed size on screen so it",
      "  is still readable when you are zoomed out",
      "  (This was a sprite tint once. The tint drew a blue rectangle round every",
      "  ship, because the sheet has no alpha to tint. A separate flag does not.)",
      "A TOWN UNDER THE BLACK FLAG STOPS BEING A COLONY",
      "  Only its defences were capped before. Its population and its wealth went",
      "  on drifting up toward the numbers it had as somebody's colony — so a",
      "  conquered town quietly rebuilt itself into exactly the prize it had been,",
      "  subsidised shipping and resident governor and all, while flying a flag",
      "  that guarantees none of it",
      "  Hold Port Royale for two years now and it settles at about a third of",
      "  the money and two thirds of the people. It is a base, not a colony",
      "  Give it back to a crown — any crown — and it recovers. A colony one",
      "  crown took off another still gets a governor and a budget",
      "CONSORT MORALE — the second ship has its own crew's opinion",
      "  Consorts have carried their own people since v0.17.0 and the flagship's",
      "  morale ever since, which showed up as a ship with ten men aboard",
      "  reloading as briskly as a full deck",
      "  Their morale is their own now: it decays when the plunder is overdue,",
      "  it comes back when you divide the take, and it drives their guns in a",
      "  sea battle",
      "  A siege pools morale across the fleet weighted by men, so a mutinous",
      "  pinnace does not drag a hundred-hand frigate down to its own mood",
    ],
  },
  {
    version: "0.18.0.0",
    date: "2026-09-03",
    changes: [
      "THE CHART SHOWS THE INVASION — a course you can steer to, not deduce",
      "  v0.17.0 put real hulls in the water and then left you to work out where",
      "  they were: which crown, which of their harbours, how many days ago",
      "  Now every landing you have been told about is pencilled on the map — a",
      "  dashed course from the harbour it sailed from, a ring on the town it is",
      "  bound for, an arrowhead where the reckoning puts it today, and the men",
      "  and days beside it",
      "  Only what you have heard. An expedition nobody has mentioned is not on",
      "  your chart, which is what keeps calling at ports worth doing",
      "  The annotation is a fixed size on screen at every zoom: a note pencilled",
      "  on a chart is the width of a pencil whatever the scale of the chart",
      "A HOME PORT — what marrying a governor's daughter is actually for",
      "  Until now the wedding paid in standing and in retirement points and",
      "  changed nothing about the day after it",
      "  Her father settles a DOWRY, scaled by what the town is worth and by the",
      "  rank you hold with his crown — a rank is what he is really buying",
      "  His YARD careens the whole fleet, hull and rig, flagship and consorts,",
      "  and sends no bill. One named harbour, so it is a reason to plot a",
      "  course home rather than a discount that follows you around",
      "  His STOREHOUSE holds 300 tons ashore. A hold is 40 and a good run is",
      "  more than that, so somewhere to leave the overflow changes which",
      "  voyages are worth attempting",
      "  All of it lapses if the town changes hands — to another crown, to the",
      "  brotherhood, or to you. Sacking your wife's home town is allowed, and",
      "  the goods stay in the storehouse, unreachable, until her father's flag",
      "  goes back up",
      "FIXED: a shipyard repaired the flagship's hull and nothing else. Not the",
      "  rig, not the consorts. A shredded suit of sails could only ever be",
      "  patched by the jury work done at sea, which is capped well short of",
      "  seaworthy on purpose — so a ship could sit in a shipyard permanently",
      "  half-rigged. Repairs now cover the whole fleet, worst damage first",
      "?home=port_royal drops you in your wife's town with a battered fleet and",
      "  a full hold",
    ],
  },
  {
    version: "0.17.0.0",
    date: "2026-09-03",
    changes: [
      "THE INVASION HAS HULLS — meet the landing at sea instead of on the wall",
      "  A crown's expedition used to be a headline and an arrival date with",
      "  nothing in between. Now, while you are near enough to see it, it is a",
      "  squadron on the chart: transports carrying the soldiers, escorts",
      "  carrying the guns",
      "  Sink a transport and those men are out of the landing for good. Sink",
      "  the escorts and the boats have nothing covering them",
      "  Break the whole squadron and the expedition is struck from the world —",
      "  the town gets the same cooling-off period as if it had thrown the",
      "  landing back on the beach",
      "  The escorts are warships and will close on you; the transports run for",
      "  the beach. Hail one and it tells you where it is going",
      "  Leave and come back and the squadron is exactly as you left it: the",
      "  ledger lives in the event, not in the hulls",
      "THE GOVERNOR ASKS — a defence you are paid for, not one you stumble into",
      "  A governor of a crown that counts you as its own, with a colony under",
      "  threat, now commissions you to hold it: gold on the town's size and",
      "  the size of the landing, plus 15 standing",
      "  Reach the town before the boats do, then hold it. It pays whether you",
      "  fought the battle yourself or the garrison did it while you watched",
      "  from the anchorage — but not if you never got there",
      "  One commission at a time, and never for a town you took off that crown",
      "  yourself",
      "  New Journal tab in the captain's log: what you have agreed to do, and",
      "  how long you have",
      "CONSORT CREWS — the men on your second ship are now real men",
      "  A consort's complement used to be recomputed from its class every time",
      "  anyone asked, so a ship that lost half its people storming a town had",
      "  them all back by the next siege. Losses now stick",
      "  Hiring in a tavern fills the flagship first and then the",
      "  shortest-handed consort, so a gutted ship can be manned again",
      "  A short-handed consort reloads slower in a sea battle and lands fewer",
      "  men on a beach",
      "FIXED: nothing on the map was moving. Every periodic system gated itself",
      "  on `tick % N == 0`, and the engine's clock has been fractional since it",
      "  went to a variable timestep — so the remainder was never zero. NPC",
      "  spawning, NPC steering and the news exchange had all been silently dead",
      "  in the running game. The sea has ships on it again",
      "?intercept=cartagena puts you on top of an expedition half a passage out;",
      "  ?commission=port_royal puts you in front of a governor with a colony in",
      "  danger",
    ],
  },
  {
    version: "0.16.0.0",
    date: "2026-09-03",
    changes: [
      "THE TOWN FIGHTS BACK — the landing you sailed home for is now a battle",
      "  Until now a relief squadron resolved offscreen even with your topsails",
      "  in the harbour. Stand off a town you hold and you fight it round by",
      "  round from behind the walls",
      "  T fires on the boats, G on the escorts, L puts your landing party on",
      "  the walls, ESC cuts the cables and leaves the town to it",
      "  The escort screens the transports: shot aimed past its guns mostly",
      "  misses, so opening the boats up costs you rounds of wall you will want",
      "  back when the men are on the sand",
      "  Your ships fire with the shore battery and draw a third of the answer.",
      "  Landing the party fills the walls and empties the gun crews by the same",
      "  proportion — the men on the ramparts are the men off the broadside",
      "  The squadron decides when it has waited long enough: eight rounds, or",
      "  the moment the walls are down past two fifths. There is no stalling",
      "  Break the transports before they ground and the expedition is finished",
      "  without a beach at all",
      "CROWNS TAKE COLONIES OFF EACH OTHER — the wars finally move flags",
      "  Ten historical wars have been on the news board since v0.9.7 and never",
      "  moved a single flag. Now a crown at war fits out expeditions against",
      "  its enemy's weakest colonies, and they are ordinary news: taverns on",
      "  both sides, NPC captains, 10-20 days at sea",
      "  It goes for the soft places, so a town you sacked last month is exactly",
      "  what somebody else sails for while you are over the horizon",
      "  Deliberately slower than you are — half your rate, a 90-day cooling-off",
      "  period per town and two expeditions at sea at most. A map that churned",
      "  would make taking a town yourself mean nothing",
      "  A colony taken by a crown starts the same countdown yours does: the",
      "  crown that founded it wants it back",
      "DEFENDING AN ALLY — a letter of marque is now worth standing on a wall",
      "  A landing on a colony of a crown that counts you as one of its own —",
      "  a letter of marque, or 'allied' on the reputation scale — is playable",
      "  too, with the transports as your pay and 25 standing as the thanks",
      "  Being merely nearby is not joining in: a defence you have no stake in",
      "  resolves without you, and takes none of your men",
      "A town under a crown now recovers its defences to the full royal",
      "  baseline; only one under the black flag is capped at 45%. Somebody in",
      "  Madrid pays for a garrison, and that is true of a conquered colony too",
      "Fixed: the three crew-supply warnings drew their raw i18n keys on screen",
      "  — 'event.food_out' instead of the sentence",
      "Fixed: the map's compass and date overlay stayed on top of a land battle",
      "  started from the map",
      "?defend=cartagena fights a landing directly; &ally=1 makes it somebody",
      "  else's colony, &garrison=N and &soldiers=N set both sides",
    ],
  },
  {
    version: "0.15.0.0",
    date: "2026-09-03",
    changes: [
      "THE CROWN COMES BACK — a town you took can be taken off you",
      "  Storm a town and the crown that lost it starts counting. After 12 days",
      "  it may fit out a relief squadron, and every day after that is a roll",
      "  A capital is worth coming back for; a fishing village is an",
      "  inconvenience. A crown already at war sails half as often",
      "  The squadron is news before it is a landing: 6-14 days at sea, gossiped",
      "  in every tavern its crown still holds and carried by NPC captains",
      "  The longer a town stays lost the harder they try — the expedition",
      "  doubles in size over six months",
      "THE GARRISON — crew left ashore, and the only thing holding the town",
      "  A town that changed hands shows THE GARRISON in its port menu: leave men",
      "  on the walls, or take them back aboard. Capacity is twice what the place",
      "  keeps under arms, so an outpost is cheap to hold and a capital is a war",
      "  The screen names the odds with your fleet in the roads and without it",
      "  Stationed men count as soldiers at face value, and desert at 0.4% a day",
      "  Being there when the squadron lands throws your landing party into the",
      "  defence, and pays 3 Gold a soldier out of the wrecked transports",
      "  A taken town now only rebuilds its defences to 45% of what the crown",
      "  used to pay for. Waiting is not a plan",
      "The flag on the map now follows a town that changes hands while you are",
      "  at sea, not only after a siege",
      "Migration v12 adds the garrison, the capture day and the relief clock.",
      "  A town already in other hands in an old save starts its clock from the",
      "  day the save is loaded, not from whenever it actually fell",
      "?relief=cartagena drops you off a town you hold with a squadron arriving",
      "  today; &garrison=N and &soldiers=N set both sides of the fight",
    ],
  },
  {
    version: "0.14.0.0",
    date: "2026-09-03",
    changes: [
      "GOVERNORS' DAUGHTERS — charm finally does something",
      "  Every town above an outpost has one, derived from the port key: the",
      "  same name and the same face in every save, so she is a place, not a roll",
      "  Ask the governor after her once you stand at 20 with his crown",
      "  Four approaches, odds shown: compliment and dance lean on charm, a gift",
      "  costs 500 Gold, and boasting is carried by notoriety — a nobody who",
      "  boasts looks a fool. A miss costs ground, so the right move depends on",
      "  which of your advantages is actually worth spending",
      "  Every point already won makes the next one harder, and a beauty is",
      "  half again as much work as a plain girl at the same standing",
      "  At 30 she repeats what her father said at dinner — see below",
      "  At 85, and with rank 2 from her father's crown, you can ask for her hand",
      "  Marriage happens once, ever, and is worth 500-1500 at retirement",
      "THE FAMILY — the first hand-authored quest, not a generated hole in sand",
      "  A marquis of the crown that hates yours took your family and scattered",
      "  them across three of his towns. Sister, brother, father, in that order",
      "  Two ways in: pay an informer 200 Gold in any tavern, or hear it free",
      "  from a daughter who has come to trust you",
      "  The tavern of the town the trail names offers the fight itself, and it",
      "  is settled the way every personal fight here is — a duel on the quay",
      "  800 / 1500 / 3000 Gold, and standing with your own crown at the end",
      "  Losing costs nothing but the walk back: the house is there tomorrow",
      "  Who the villain is follows your nationality, so a Spanish captain hunts",
      "  an English marquis across an English map",
      "RETIREMENT scores three new lines: towns taken (400 each), family",
      "  brought home (700 each) and the marriage. None of them can be ground",
      "  out in a final year of raiding, which is the point",
      "QUEST REGISTRY — one place that knows what quests exist",
      "  A dig used to be fed a registry built only from the maps in hand, so a",
      "  second thread could never advance on it. Both now see everything",
      "Tavern replies are finally drawn: the map you bought, the price you could",
      "  not meet and the informer's answer were all written and thrown away unseen",
      "Migration v11 adds citiesCaptured and courtship, both starting empty",
    ],
  },
  {
    version: "0.13.0.0",
    date: "2026-09-03",
    changes: [
      "LAND BATTLES — towns can be stormed, and they change hands",
      "  'ATTACK' at a port used to start a sea battle against the port id: an",
      "  enemy with no hull and no guns. It now opens a real siege",
      "  Offered at every town you sail up to, not only hostile forts",
      "BOMBARDMENT — trade broadsides with the shore battery, a round at a time",
      "  Your shot goes into the masonry and the embrasures; theirs goes into",
      "  your hull and your crew, and both sides fire the same round, so",
      "  silencing the last gun still costs you that gun's last salvo",
      "  A fort mounts up to 26 guns, a town 12, an outpost 4, scaled by defence",
      "  Intact walls make the best gun platform in the bay: knock them down and",
      "  the return fire gets measurably worse",
      "  A frigate needs 8-12 rounds to silence Cartagena and pays ~80 hull",
      "  A sloop is driven off long before the guns are out. Bring a fleet",
      "THE LANDING is auto-resolved in waves, with the odds shown before you",
      "  commit. Walls are worth up to 2.5x the garrison, which is the whole",
      "  argument for spending hull before spending men",
      "  A town gutted by plague or famine is genuinely easier to take: the",
      "  garrison scales with the population the economy has actually left it",
      "  Landing on an intact first-rate fort is a 39% proposition; after a",
      "  proper bombardment the same landing is 70%",
      "SPOILS — sack it, keep it for the brethren, or hand it to a sponsor",
      "  Sacking pays most and leaves the old flag over the ruin",
      "  The brethren or a crown you hold a letter of marque from take the town",
      "  itself: the port's faction changes, and everything follows it — the",
      "  flag on the map, the governor you talk to, prices, NPC spawns",
      "  A sponsor pays half and buys a rank; every other crown notices",
      "  A sacked town keeps a seventh of its garrison and a third of its money,",
      "  and climbs back toward baseline over the following months",
      "THE FLEET MATTERS ASHORE — guns and landing parties count every hull,",
      "  so a consort is a second broadside and a second crew on the sand",
      "?siege=cartagena drops you straight into an assault with a ship able to",
      "  try one, for testing",
      "scripts/drive.mjs walks the running game with an arbitrary key sequence",
    ],
  },
  {
    version: "0.12.1.0",
    date: "2026-09-03",
    changes: [
      "DAMAGE, VISIBLE — shot holes and torn canvas drawn onto the ship sprite",
      "  v0.9.9 named the hull and rig stages but the ship looked the same at",
      "  90% and at 20%: two bars, and a smoke puff below 25%",
      "  leaking 2 holes, crippled 4 + torn canvas, foundering 6 + waterline stain",
      "  dismasted adds a spar over the side with slack canvas trailing off it",
      "  Marks are jittered from a hash of the ship id, so they stay put across",
      "  frames and two ships in the same battle are marked differently",
      "  Drawn in screen space, not rotated by heading: sailship.png is a 3/4",
      "  view whose hull always sits low in the cell, so rotating put holes in",
      "  the rigging on half the headings and in empty padding on the rest",
      "  Applies to the player, the enemy and every fleet consort",
      "AI ASSETS — the generated damage frames were abandoned, and why",
      "  Every torn-sails / broken-mast prompt came back as an untouched ship:",
      "  the model has no notion of a damaged version of something it only saw",
      "  intact. Four generated frames, four clean ships. Drawing beats prompting",
      "  here because the marks derive from the numbers the engine already steers by",
      "  LoRA v3 dataset builder added: 8 ship frames mirrored onto two grounds",
      "  give 32 top-down samples instead of 8, icons cut from 48 to 28 entries",
      "  Top-down share rises from 10% to 32% of the set, with double the repeats",
      "  It fixes the 3/4-view bias; it cannot fix nine ship classes looking alike,",
      "  because the project contains exactly one ship sprite",
    ],
  },
  {
    version: "0.12.0.0",
    date: "2026-09-02",
    changes: [
      "QUESTS — the FSM the placeholder promised since v0.5.6",
      "  QuestSystem.ts: stages, data triggers, effects, a validator",
      "  Triggers: reach_port, dig_at (point + radius), flag_set, days_passed",
      "  Rewards reuse DialogueEffect instead of a second effect vocabulary",
      "  One transition per event, so nothing skips two stages on one dig",
      "  A completed quest stops responding entirely — a dig cannot pay twice",
      "  validateQuest() catches dead ends, missing stages, terminal stages",
      "  that still list transitions",
      "TREASURE MAPS — the first reason to go ashore",
      "  Walking on foot has existed since v0.9.3 and had nothing to do",
      "  Buy a map in the tavern: crude 300g (220 radius), fair 800g (110),",
      "  surveyor's 2000g (45). A richer port deals in better charts",
      "  The chest is buried near a named city; press X ashore to dig",
      "  A miss reports warm or cold plus a bearing, so a crude map is still",
      "  usable — land, dig, walk toward the hint, dig again",
      "  A quarter of maps are bait: digging one starts a duel at the hole",
      "  Win and the chest is yours; lose and they take a quarter of your gold",
      "  Rewards 400-2500g, scaled up for a better chart",
      "HELP — L and X added to the controls list",
      "TESTS — 448 -> 489 across 13 files",
    ],
  },
  {
    version: "0.11.0.0",
    date: "2026-09-02",
    changes: [
      "DIALOGUES — conversations are data now, not hardcoded branches",
      "  core/systems/DialogueSystem.ts: nodes, gated replies, effects, a validator",
      "  Conditions are data too (flag / reputation / gold / skill / day, not / all / any)",
      "  Effects: set a flag, move gold or reputation, log — plus a custom escape hatch",
      "  A gated reply is refused if it is not currently visible, so a stale option",
      "  list cannot fire it. A reply pointing at a missing node ends the talk",
      "  rather than stranding the player in a box with nothing to click",
      "  Deliberately not a scene: the same tree draws in the port dialog today",
      "  and in a full screen later, and asserts in a test with no Phaser at all",
      "GOVERNOR — the first real conversation, replacing the old flat panel",
      "  Ask about a letter of marque, the news, how you stand, or retiring",
      "  The letter reply is gated three ways and only one shows at a time",
      "  Removed getGovernorDialogueKey(), which nothing called any more",
      "PLUNDER — the crew wants its share every 60 days",
      "  Past that, morale bleeds 0.4%/day down to a floor of 15%",
      "  Morale already drives reload speed, boarding and repairs, so an ignored",
      "  crew is measurably worse at everything long before it mutinies",
      "  Divide in the tavern: the captain keeps 35-60% by rank and fame, the",
      "  rest is paid out, 65% of the hands go ashore, the survivors are content",
      "AGEING — the captain's years finally do something",
      "  20-35 prime, 35-50 the sword arm slows and experience sharpens, 50+ decline",
      "  fencing/gunnery fall to a floor of 0.55x; navigation/charm/medicine rise to 1.30x",
      "  Applied at the point of use — the cabin sheet still shows what he learned",
      "  calculateAge() has existed since v0.5.6 and until now only printed a number",
      "  Also: the captain's swordsmanship now reaches boarding at all. Nothing ever",
      "  called setSwordsmanship(), so every captain fought as a flat 5",
      "RETIREMENT — a career can end, and be scored",
      "  Offered by the governor after a year at sea; ends the game with a ledger",
      "  Gold, fleet, ranks, goodwill, fame and years, each weighted differently",
      "  A year at sea is worth 40, a year past 50 costs 70 — so the score peaks",
      "  right at the decline. Stopping too early and sailing forever both cost you",
      "SAVE — migration v10 adds the plunder clock, counting from the day loaded",
      "  Counting from day one would open every old save with a furious crew",
      "TESTS — 359 -> 448 across 12 files",
    ],
  },
  {
    version: "0.10.0.0",
    date: "2026-09-01",
    changes: [
      "DUELS — captains settle a boarding with steel instead of one dice roll",
      "  New DuelScene over the paused battle; all rules in core/systems/DuelSystem.ts",
      "  Q/W/E strike high/middle/low, A/S/D guard high/middle/low",
      "  Guard the line he strikes and the riposte wins you ground — that is the core",
      "  Attack into an open line and the blow lands; both attacking, the better hand wins",
      "  Fencing (0-10) scales what a blow is worth; stamina drains on attacks, returns on guards",
      "  Swing every round and you tire, and a tired blade loses exchanges it would win",
      "  The enemy reads you: the better his fencing, the more he guards the line you just used",
      "  He presses when ahead, guards when winded. Seeded, so a duel replays identically",
      "  Duel decides who wins the boarding; the melee's crew losses are costed as before",
      "  fencing used to touch exactly one multiplier in BoardingSystem — now it is played",
      "REPAIR AT SEA — the carpenter's crew patches what it can under way",
      "  Runs once per game day; hull capped at 50% of max, rigging at 60%",
      "  Rate scales with hands left times morale — a full, willing crew mends a few % a day",
      "  Enough to climb off the foundering stage and limp home, never enough to fight fresh",
      "  Nothing happens in port, below 20% crew, or on a hull already gone down",
      "SURVIVORS — a sunk enemy leaves men in the water",
      "  40% of the crew still alive can be found; only as many come aboard as there are berths",
      "  Pressed men dilute crew training, the same as tavern recruits",
      "TESTS — 295 -> 359 across 10 files (DuelSystem 35, ShipRepairSystem 29)",
    ],
  },
  {
    version: "0.9.9.1",
    date: "2026-09-01",
    changes: [
      "DEV FIX — a hot reload no longer stacks a second game on top of the first",
      "  Every save under src/ re-ran main.ts and booted another Phaser.Game",
      "  Two scene trees, two sets of key listeners; the visible canvas was not",
      "  the one your keys reached, so the controls looked dead until a hard reload",
      "  main.ts now tears the old game down in import.meta.hot.dispose",
      "  Production is unaffected — this only ever happened on the dev server",
    ],
  },
  {
    version: "0.9.9.0",
    date: "2026-09-01",
    changes: [
      "DAMAGE STAGES — hull and rigging are named conditions now, not one number",
      "  HULL: >=75% sound, >=50% leaking, >=25% crippled, below that foundering",
      "  Speed x1.00 / x0.88 / x0.70 / x0.45, turn rate x1.00 / x0.85 / x0.65 / x0.45",
      "  RIG: >=75% intact, >=40% torn, >=10% tattered, below that dismasted",
      "  Rig speed x1.00 / x0.75 / x0.45 / x0.00 — a dismasted ship drifts in battle",
      "  Hull and rig stack, so a crippled hull under torn canvas is slower than either",
      "FOUNDERING — below 25% hull a ship takes water every tick and goes down alone",
      "  ~23 s from the threshold to the bottom: time to break off, not time to ignore",
      "  Works both ways — a beaten enemy can sink after you disengage",
      "SINKING — the hull settles, slews and leaves a ring of disturbed water",
      "  The result banner now waits for the ship to go under before covering it",
      "  Losing sinks the hold with the ship: 10-30% survives, more with a live crew",
      "STAGED FX — crippled hulls smoke, foundering hulls smoke harder and burn",
      "  Was: one smoke puff below 25% and nothing above it",
      "MAP — the same stages apply to the world map, with one deliberate exception",
      "  A dismasted ship still crawls at 15% instead of stopping dead",
      "  Repairs only exist in port, so a true zero would strand the player forever",
      "HUD — battle status line shows the condition of hull and rigging",
      "  Speed readout now uses the real damage multiplier, not just sail HP",
      "  It also calls the engine's own wind curve instead of a hand-copied duplicate",
      "  That copy still had the discontinuity fixed in v0.9.8.2 — HUD and ship disagreed",
      "TESTS — 257 -> 295: tier boundaries, stacking, flooding rate, no-strand guarantee",
    ],
  },
  {
    version: "0.9.8.3",
    date: "2026-09-01",
    changes: [
      "TESTS — 119 -> 257, one test file -> seven (TODO P0-3)",
      "  Migrations: v1 -> v9 chain, every version as an entry point, idempotence",
      "  CombatSystem: reload cadence vs crew / morale / training, clamps, monotonicity",
      "  BoardingSystem: grapple preconditions, melee resolution, casualties, loot",
      "  FleetSystem: roster limits, slowest-hull speed, tallest-mast vision, summary",
      "  SailSystem: level table, transition timing, reversal, setImmediate clamps",
      "  EconomyTickSystem + EventEffectsSystem: production, prices, recovery, events",
      "SAVE FIX — migration v9 repairs ports that predate shipyardQueue / availableCrew",
      "  Ports carried from a pre-v2 save were only ever extended, never normalised",
      "  They reached v8 missing two fields; the tavern pool read as undefined",
      "  v9 normalises every port to the full shape; complete ports pass through",
      "SAIL FIX — tapping W repeatedly no longer sets canvas for free",
      "  Transition length was measured from the previous ORDER, not the actual canvas",
      "  Furled -> full took one 2 s step when tapped fast, instead of three",
      "  Now counted from where the canvas is; a reversal only costs what was set",
      "  Sail level drives turn rate in battle, so the shortcut was worth money",
      "DOCS — sail level 2 is 0.50, not the 0.66 the header claimed",
    ],
  },
  {
    version: "0.9.8.2",
    date: "2026-09-01",
    changes: [
      "WIND FIX — the polar curve no longer jumps at 120 deg (TODO P0-2)",
      "  Was: reach branch fell back to 0.4x at 120 deg while running picked up at 1.1x",
      "  A ship at heading 119 sailed 0.4x and at 121 already 1.1x — 2.75x over two degrees",
      "  Now: two quarter sines — rise 0.4 -> 1.5 at the peak, fall 1.5 -> 1.1 at 120 deg",
      "  Peak sits halfway across the reach band, so square rigs peak further off the wind",
      "  Speed now falls off monotonically from the peak all the way down to running",
      "  Full curve (30 deg no-go): 60=0.40 90=1.50 110=1.30 120=1.10 150=1.00 180=0.90",
      "TESTS — 115 -> 119 passing, no todo left",
      "  Continuity across the 120 deg seam for every rig (30-60 deg no-go)",
      "  Whole-curve continuity scan, monotone falloff past the peak, 1.1x handover",
    ],
  },
  {
    version: "0.9.8.1",
    date: "2026-09-01",
    changes: [
      "PORZĄDKI — housekeeping release, no gameplay changes",
      "TESTS — NavigationSystem suite green again (115 passing, was 7 failing)",
      "  Wind expectations still encoded the pre-v0.9.4 cosine model",
      "  Rewritten against the polar diagram: no-go zone, 1.5x beam reach, 0.9x running",
      "  Added coverage: rig-specific no-go width, port/starboard symmetry, strength scaling",
      "DEAD CODE — removed three files that were never reachable",
      "  SaveLoadScene: 'coming in Phase 7' stub — save/load lives in OptionsMenuScene",
      "  DialogueScene: rendered the text 'Dialogue Scene (TODO)'",
      "  PalmRenderer.backup.ts",
      "DOCS — full documentation refresh (was stuck at v0.8.4, March)",
      "  Ship table: 5 outdated classes -> all 9 with real stats",
      "  Systems: 11 documented -> 21, including every system added since v0.9.4",
      "  Combat doc rewritten (reload/damage formulas, boarding, surrender)",
      "  Roadmap rewritten — phases 6, 7, 10.1-10.2 and 14 were done but listed as pending",
      "  Persistence: migrations documented through v8",
      "TODO.md — new handoff file: project state, tech debt, ordered release plan",
      "KNOWN BUG documented — wind polar curve is discontinuous at 120 deg",
      "  Heading 119 sails at 0.4x, heading 121 at 1.1x. Fix scheduled for v0.9.9",
    ],
  },
  {
    version: "0.9.8.0",
    date: "2026-05-31",
    changes: [
      "RELOAD SPEED — broadside cadence now reflects the crew's state",
      "  Base 9 s scales by crew size × morale × training (best 9 s, worst ~24 s)",
      "  CREW: 0.70 at 20%, 1.00 at full",
      "  MORALE: 0.80 at 0%, 1.00 at 100%",
      "  TRAINING: 0.75 untrained, 1.00 veteran",
      "CREW TRAINING — new long-term stat on the captain",
      "  +0.0005 per day at sea (~+0.18 per year of sailing)",
      "  +0.02 per battle won (~10 wins → +0.20)",
      "  Dilutes when fresh recruits join the crew (weighted average)",
      "  Visible as a bar in the Cabin tab (SPACE)",
      "BATTLE UI — morale and training now visible during combat",
      "  Player + enemy ship labels show Morale % alongside crew/cannons",
      "  Player morale colour-coded green / amber / red",
      "  Top-right HUD includes Training: NN%",
      "DOCS — full formula in BattleHelpScene (H during battle)",
      "Migration v8 backfills training field on old saves (default 0.30)",
    ],
  },
  {
    version: "0.9.7.1",
    date: "2026-05-19",
    changes: [
      "HELP screen — new EKONOMIA tab with full living-world documentation",
      "  Two-column layout: state model on left, event catalogue on right",
      "  All 13 event types listed with one-line effect summaries",
      "  Color-coded severity dots (yellow / amber / red)",
      "  Player tips: how to profit from booms, famines, gold strikes, wars",
    ],
  },
  {
    version: "0.9.7.0",
    date: "2026-05-18",
    changes: [
      "LIVING ECONOMY — cities now grow, shrink, and react to world events",
      "  Numeric population, wealth (0-1000), and defence (0-100) per port",
      "  Daily economy tick: production → consumption → price update → recovery",
      "  Prices respond to supply/demand: shortages cost more, gluts cost less",
      "  CityInfo panel shows live values with ↑/↓ trend arrows vs baseline",
      "  CityInfo panel lists active world events affecting that port",
      "NEW WORLD EVENTS (Phase 2 — events now reshape the world):",
      "  Gold strike: small/medium town starts producing gold, pop +0.5%/day for a year",
      "  Indigenous raid: Spanish frontier outposts lose pop, wealth, defence",
      "  Famine: food/water prices ×2-4, population drops",
      "  Harvest (autumn): food/sugar prices ×0.6, +inventory boost",
      "  Royal decree: faction-wide tariff change, lasts up to a year",
      "EVENT EFFECTS — every event now applies daily state deltas:",
      "  Epidemic → population drop, crew recruitment halved, prices spike",
      "  Pirate raid (one-shot) → wealth -80, inventory -30%, defence decays",
      "  Hurricane → port closed, inventory damage, ships hit",
      "  Trade boom → production ×1.5, prices -20%",
      "  Slave revolt → production ×0.3, wealth drains",
      "  New governor → wealth windfall +50",
      "WAR DRIVES SEA TRAFFIC:",
      "  Warring factions spawn 2× more ships",
      "  Wartime spawns shift 45% → 70% navy, trader share drops",
      "  Production -15% / prices +10% in warring nations",
      "Migration v7 for old saves — fills new numeric fields from baseline",
      "i18n: 6 new news headline keys (EN + PL)",
    ],
  },
  {
    version: "0.9.6.0",
    date: "2026-05-11",
    changes: [
      "SEA BATTLES — Sid Meier's Pirates! style combat scene",
      "  ?battle=1|trader|navy|pirate|hunter URL params for direct testing",
      "  Camera follows player (always centered), arena 3× viewport",
      "  Manual broadsides: Q (port) / E (starboard), arc-restricted (no fore/aft)",
      "  3 ammo types: 1=Round, 2=Chain, 3=Grape — switching resets reload",
      "  Flying cannonballs with parabolic arc, splash on miss/overshoot",
      "  Cannon range = half screen; visible port + starboard arc indicators",
      "  Per-cannon damage scaling: broadside = ship.cannons / 2",
      "  Hull armor per ship class (Galleon 0.60 thick → Sloop 0.10 paper)",
      "  Quadratic distance falloff + ×1.6 point-blank bonus + accuracy roll",
      "  Wind- and hull-modulated steering (damaged hull = sluggish rudder)",
      "  Sail level affects speed; W/S cycles Furled / Battle / Full",
      "  9-second reload per broadside, color-coded L (red) / R (green) bars",
      "  AI archetypes: aggressive / defensive / tactical; crew-ratio override",
      "  Enemy with ≥1.5× player crew aims to board; ≤0.5× tries to flee",
      "  Boarding (B) when enemy weakened; capture adds ship to fleet",
      "  Auto-surrender at hull ≤10% OR sails ≤10% OR crew <10",
      "  60s far-distance → 60s countdown → auto-disengage",
      "  Battle Help (H) — in-battle manual with full damage formula spec",
      "  HUD top-right: ammo / sails / speed (kn) / cannons",
      "  Under each ship: hull/sails bars + crew & cannon counts + reload",
      "  Damage floaters: hull (red) / sails (cyan) / crew (orange), 2s",
      "  Outcomes apply to world: damage, loot, capture, reputation",
    ],
  },
  {
    version: "0.9.5.0",
    date: "2026-03-28",
    changes: [
      "9 ship classes: Pinnace, Sloop, Barque, Brigantine, Fluyt, Frigate, Fast Galleon, Galleon, Merchantman",
      "Fleet system: max 3 ships, buy/sell/abandon escorts in shipyard",
      "  Fleet speed = slowest ship, vision = tallest mast",
      "World Events: 10 historical wars (1568-1697) + 7 random event types",
      "NPC News: traders/navy carry news from ports, share on approach",
      "  Tavern rumors now include local world event news",
      "Seagull sounds: synthesized cries at zoom 5+ (Web Audio)",
      "Sail level affects turn rate: reefed = +50% maneuverability",
      "Spyglass range based on ship mast height (fleet max)",
      "Wind physics: peak 150% at beam reach, realistic polar diagram",
      "Help screen updated: 12 columns, all 9 ship classes with max knots + luneta range",
    ],
  },
  {
    version: "0.9.4.0",
    date: "2026-03-27",
    changes: [
      "Wind physics: realistic polar diagram with ship-specific dead zones",
      "  Sloop 35° (fore-and-aft), Brigantine 40°, Frigate 50°, Galleon 60°, Merchantman 55°",
      "  Dead zone → close hauled → beam reach (peak) → running",
      "  'Pod wiatr!' warning in UI when in irons",
      "Ship parameters: minWindAngle, mastHeight, rigType, tonnage, draft added",
      "Help screen (H key): 4 sections — Controls, Ships, Sailing, World",
      "  Ships table with all parameters, sailing guide with wind angles",
      "Ship speed display under sail level (knots)",
      "Wind label enlarged (14px)",
      "Sail transition: 3s → 2s",
    ],
  },
  {
    version: "0.9.3.1",
    date: "2026-03-26",
    changes: [
      "Sail system: 4 named levels (Furled/Reefed/Half/Full), 3s smooth transitions",
      "Sail UI: level name displayed under compass",
      "On-foot port visits: entering on foot → leaving returns on foot (no ship teleport)",
      "Port labels: 'ODEJDŹ' when on foot, 'ODPŁYŃ' when sailing (approach + port scenes)",
      "Port interaction radius reduced on foot (20→10px)",
      "Wake particles: 3× more, 50% shorter, tighter spread",
      "Wave overlay disabled (blocky) — replaced with photo-based parallax",
    ],
  },
  {
    version: "0.9.3.0",
    date: "2026-03-25",
    changes: [
      "FIX JITTER: root cause was Phaser pixelArt:true forcing roundPixels — camera.setRoundPixels(false)",
      "Variable timestep: 1 tick per frame, no accumulator (like seagulls/clouds)",
      "Wave overlay v2: photo-based parallax (two TileSprite layers, ADD blend, no canvas strokes)",
      "Integer zoom levels: scroll snaps to 1×–12× with smooth lerp transition",
      "Ship sprites: auto-cut from ChatGPT image, per-frame elliptical masks, white bg removed",
      "Crew party PNG sprite (pirate crew with skull flag)",
      "Fix instant re-embark (landedTick cooldown), turbo departure (pushDist 15→5, grace speed 1.5→0.15)",
      "Crew lands 3px from coast (was 20px deep inland)",
      "Disabled old wave overlay (blocky canvas strokes) — replaced with photo-based",
    ],
  },
  {
    version: "0.9.2.3",
    date: "2026-03-25",
    changes: [
      "New ship sprites: 8 directions from ChatGPT image, auto-cut with elliptical mask",
      "Ship sprite: white bg removed, 256x256 frames, LINEAR filtering",
      "Crew party PNG sprite (pirate crew with skull flag) replaces procedural rectangles",
      "Crew 2x bigger (12 world px), ship scale adjusted (0.086 for 256px frames)",
      "Fix instant re-embark: landedTick cooldown (15 ticks) + auto-embark radius 20→8px",
      "Fix turbo departure: grace speed 1.5→0.15, pushDist 15→5px, duration 40→15 ticks",
      "Crew lands 3px from coast (was 20px deep inland)",
      "City info panel: i18n refactor, fort info, shipyard types, last visit",
      "Port seagulls: 3-10 per port over water + reduced ambient (80-150)",
      "Fix ship directions (180° — ships faced inward in source image)",
    ],
  },
  {
    version: "0.9.2.2",
    date: "2026-03-24",
    changes: [
      "Ship speed halved: Sloop 0.30, Brigantine 0.275, Frigate 0.25, Galleon 0.19, Merchantman 0.16",
      "Smooth movement v5: velocity prediction with gameSpeed fix + softer drift correction (0.03)",
      "Embark: minimal sails (0.1) for slow departure from land",
      "Fix Petit Goâve + Léogane positions (were inland, moved to coast)",
      "TODO: sailing into wind = speed 0 (advanced wind physics deferred)",
    ],
  },
  {
    version: "0.9.2.1",
    date: "2026-03-23",
    changes: [
      "6 city PNG sprites: large/medium/small × city/fort (384×256, pre-scaled for sharpness)",
      "Cities 50% bigger on max zoom (22/15/10 world px)",
      "Smooth ship movement: exponential smoothing replaces fixed-timestep interpolation",
      "Camera direct follow (no lerp delay), delta cap for frame spike protection",
      "Wave layers: ADD blend mode (fixes blue rectangle artifacts)",
      "Wave visibility: zoom 6→12, 50% max alpha, blur for natural look",
      "Fix 5 cities on water: San Juan, Santa Catalina, Montserrat, Curaçao, Port de Paix",
      "Removed shore shadow canvas (caused pixelated squares at curves)",
      "Chaikin smoothing 3 iterations for smoother coastlines",
      "Original city assets preserved in sprites/originals/",
    ],
  },
  {
    version: "0.9.2.0",
    date: "2026-03-21",
    changes: [
      "Sea photo texture: mirror-tiled, zoom-dependent alpha (0→50%), depth under wave layers",
      "Land photo texture: tropical forest aerial, mirror-tiled, GeometryMask to land polygons",
      "City sprites: PNG assets (city_large.png), isometric colonial town, constant screen size",
      "Beach gradient: 3 GPU-rendered strokes with zoom fade, no pixelation",
      "Shore shadow: canvas shadowBlur for smooth Gaussian glow at coastline",
      "Flags: constant screen size at all zoom levels, LINEAR filtering",
      "City labels: constant screen size (1/zoom), no more growing at close zoom",
      "Ship scale: 33% smaller at max zoom",
      "Crew sprite: 10x smaller on land",
      "Turn rate: 3x faster key response (0.04 → 0.12 rad/tick)",
      "Start screen: new Barbados beach background, opaque BG fix",
      "Zoom indicator: bottom-left corner, normalized 0→10 scale",
      "URL debug params: ?skip, ?zoom=, ?debug= for testing",
      "Puerto Príncipe: moved east (was on water)",
      "Palm forest procedural generator (PalmForestTexture.ts) — ported from HTML tool",
    ],
  },
  {
    version: "0.9.0",
    date: "2026-03-20",
    changes: [
      "Volumetric clouds: spite codepen texture, layered clusters (10-20 layers), 3 size classes",
      "Cloud zoom scaling: shrink on zoom out, grow on zoom in",
      "Wind compass: procedural canvas-drawn (WindCompassWidget), no external images",
      "Ocean waves: mirror-tiled 2-layer parallax, animated with wind",
      "Ship speed halved, turn rate 4x, port departure with minimal sails",
      "Smooth coastlines: Chaikin subdivision on landmass polygons",
      "Vision circle restored (Arc), fog-of-war toggle in Options",
      "Debug toggle in Options (default ON), LPM disabled while sailing",
      "Date moved to top-left corner",
      "Ship wake: animated arc ripples around moving ships",
      "Refactor: MainMapScene 1327→739 lines (TextureFactory, CityIconRenderer, PortMarkerRenderer)",
      "Ship classes documentation: 9 types with tonnage, draft, reef mechanics",
      "14 zoom levels (1.5x-12x), ship sprite scales with zoom",
    ],
  },
  {
    version: "0.8.6",
    date: "2026-03-19",
    changes: [
      "14 zoom levels (0.5x–20.0x) — z13 Spyglass, z14 Crow's Nest",
      "City icons: atmospheric pixel art (colonial buildings, palm trees, thatched huts)",
      "3 city sizes visually distinct: large (walled town), medium (colonial), small (village)",
      "City labels: white text with shadow, sqrt-zoom scaling, always readable",
      "City labels positioned below cities, depth 600 (never obscured)",
      "11 port positions corrected to match real Caribbean geography",
      "Tortuga fixed: separate island from Hispaniola (land grid 4x4 sub-sampling)",
      "Port approach radius reduced 40% — must sail closer to trigger dialog",
      "Fort icons: stone walls with corner towers, battlements, cannon positions",
      "Small cities: no more dock/pier artifact, palm trees instead",
    ],
  },
  {
    version: "0.8.5",
    date: "2026-03-19",
    changes: [
      "10 zoom levels (0.5x–8.0x), default z8 (5.0x)",
      "Clouds: smaller (50%), more numerous, spread across entire map, fade-in",
      "Seagulls: 2 sizes, soft coastal steering, only over water near coast",
      "Ship sprite 30% smaller for better map proportion",
      "Date moved to UIOverlay (top-right, no time), zoom-independent",
      "Port departure fix: ship pushed perpendicular to coast toward open sea",
      "Cloud height variety: flat/medium/tall cumulus profiles",
      "Wind displayed in knots on compass",
    ],
  },
  {
    version: "0.8.4.1",
    date: "2026-03-19",
    changes: [
      "NPC ships: spawn from ports, port-to-port AI, fog-of-war (V toggle)",
      "UIOverlayScene: wind compass + version label (zoom-independent)",
      "Clean UI: minimap removed, HUD moved to SPACE menu",
      "Start with furled sails on new/loaded game",
      "Embark fix: perpendicular-to-coast departure with grace period",
      "Comprehensive documentation (11 docs) + AI assets subproject",
    ],
  },
  {
    version: "0.8.4",
    date: "2026-02-20",
    changes: [
      "Classic map: caribbean_bg.png background (GitHub v0.8.2 style)",
      "Generated pack: procedural blob tiles + water_tile overlay",
      "Asset pack now controls map rendering style",
      "Dancing Script font (local, full Polish support)",
      "All fonts scaled +30% for readability",
      "Nationality-specific starting cities",
      "Renamed menu tabs (shorter labels)",
      "Options dialog enlarged 20%",
      "Puppeteer screenshot tool",
    ],
  },
  {
    version: "0.8.3",
    date: "2026-02-20",
    changes: [
      "Two-step character creation: name/era + nationality/skills",
      "Captain profile: 5 skills (fencing, gunnery, navigation, medicine, charm)",
      "Skill point allocation with 10 bonus points",
      "Ship faction now matches captain's nationality",
      "+20 reputation bonus with own nation at game start",
      "New 'Captain' tab in options menu (skills, ranks, age)",
      "Save migration v5: old saves get default captain profile",
      "Changelog visible in-game (Quartermaster tab)",
      "Allura italic font (replaces Treasure Map Deadhand, Polish support)",
      "New start screen music (pirate_adventure.wav)",
    ],
  },
  {
    version: "0.8.2",
    date: "2026-02-19",
    changes: [
      "Version label in bottom-right corner (start screen)",
      "Larger version font (8px -> 12px)",
      "Beach fringe overlay fix",
    ],
  },
  {
    version: "0.8.1",
    date: "2026-02-19",
    changes: [
      "Custom pirate font (Treasure Map Deadhand)",
      "Wind rose compass on map",
      "Caribbean map in options menu",
      "Smaller, cleaner dialog panels",
      "45 cities with full port data",
      "Shipyard: buy ships, repair hull",
      "Tavern: recruit crew, buy drinks, hear rumors",
      "Governor: ranks, letters of marque",
      "Era selection (6 historical eras)",
      "Save/load system (5 slots)",
      "Event log and calendar",
      "Asset pack switching (classic / AI sprites)",
      "Zoom level setting (far / normal / close)",
      "Polish language support",
    ],
  },
  {
    version: "0.8.0",
    date: "2026-02-18",
    changes: [
      "Initial release: Caribbean sailing, trading, combat",
      "Procedural world generation with factions",
      "Sea battle system",
      "Port trading and docking",
    ],
  },
];
