export type ChangelogEntry = {
  version: string;
  date: string;
  changes: string[];
};

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "0.9.0",
    date: "2026-03-20",
    changes: [
      "Volumetric clouds: spite codepen texture, layered clusters (10-20 layers), 3 size classes",
      "Cloud zoom scaling: shrink on zoom out, grow on zoom in",
      "Wind compass: procedural canvas-drawn (WindCompassWidget), no external images",
      "Ocean waves: mirror-tiled 2-layer parallax, animated with wind",
      "Ship speed halved, turn rate 4x, port departure with minimal sails",
      "Smooth coastlines: Chaikin subdivision on landmass polygons",
      "Vision circle restored (Arc), fog-of-war toggle in Options",
      "Debug toggle in Options (default ON), LPM disabled while sailing",
      "Date moved to top-left corner",
      "Ship wake: animated arc ripples around moving ships",
      "Refactor: MainMapScene 1327→739 lines (TextureFactory, CityIconRenderer, PortMarkerRenderer)",
      "Ship classes documentation: 9 types with tonnage, draft, reef mechanics",
      "14 zoom levels (1.5x-12x), ship sprite scales with zoom",
    ],
  },
  {
    version: "0.8.6",
    date: "2026-03-19",
    changes: [
      "14 zoom levels (0.5x–20.0x) — z13 Spyglass, z14 Crow's Nest",
      "City icons: atmospheric pixel art (colonial buildings, palm trees, thatched huts)",
      "3 city sizes visually distinct: large (walled town), medium (colonial), small (village)",
      "City labels: white text with shadow, sqrt-zoom scaling, always readable",
      "City labels positioned below cities, depth 600 (never obscured)",
      "11 port positions corrected to match real Caribbean geography",
      "Tortuga fixed: separate island from Hispaniola (land grid 4x4 sub-sampling)",
      "Port approach radius reduced 40% — must sail closer to trigger dialog",
      "Fort icons: stone walls with corner towers, battlements, cannon positions",
      "Small cities: no more dock/pier artifact, palm trees instead",
    ],
  },
  {
    version: "0.8.5",
    date: "2026-03-19",
    changes: [
      "10 zoom levels (0.5x–8.0x), default z8 (5.0x)",
      "Clouds: smaller (50%), more numerous, spread across entire map, fade-in",
      "Seagulls: 2 sizes, soft coastal steering, only over water near coast",
      "Ship sprite 30% smaller for better map proportion",
      "Date moved to UIOverlay (top-right, no time), zoom-independent",
      "Port departure fix: ship pushed perpendicular to coast toward open sea",
      "Cloud height variety: flat/medium/tall cumulus profiles",
      "Wind displayed in knots on compass",
    ],
  },
  {
    version: "0.8.4.1",
    date: "2026-03-19",
    changes: [
      "NPC ships: spawn from ports, port-to-port AI, fog-of-war (V toggle)",
      "UIOverlayScene: wind compass + version label (zoom-independent)",
      "Clean UI: minimap removed, HUD moved to SPACE menu",
      "Start with furled sails on new/loaded game",
      "Embark fix: perpendicular-to-coast departure with grace period",
      "Comprehensive documentation (11 docs) + AI assets subproject",
    ],
  },
  {
    version: "0.8.4",
    date: "2026-02-20",
    changes: [
      "Classic map: caribbean_bg.png background (GitHub v0.8.2 style)",
      "Generated pack: procedural blob tiles + water_tile overlay",
      "Asset pack now controls map rendering style",
      "Dancing Script font (local, full Polish support)",
      "All fonts scaled +30% for readability",
      "Nationality-specific starting cities",
      "Renamed menu tabs (shorter labels)",
      "Options dialog enlarged 20%",
      "Puppeteer screenshot tool",
    ],
  },
  {
    version: "0.8.3",
    date: "2026-02-20",
    changes: [
      "Two-step character creation: name/era + nationality/skills",
      "Captain profile: 5 skills (fencing, gunnery, navigation, medicine, charm)",
      "Skill point allocation with 10 bonus points",
      "Ship faction now matches captain's nationality",
      "+20 reputation bonus with own nation at game start",
      "New 'Captain' tab in options menu (skills, ranks, age)",
      "Save migration v5: old saves get default captain profile",
      "Changelog visible in-game (Quartermaster tab)",
      "Allura italic font (replaces Treasure Map Deadhand, Polish support)",
      "New start screen music (pirate_adventure.wav)",
    ],
  },
  {
    version: "0.8.2",
    date: "2026-02-19",
    changes: [
      "Version label in bottom-right corner (start screen)",
      "Larger version font (8px -> 12px)",
      "Beach fringe overlay fix",
    ],
  },
  {
    version: "0.8.1",
    date: "2026-02-19",
    changes: [
      "Custom pirate font (Treasure Map Deadhand)",
      "Wind rose compass on map",
      "Caribbean map in options menu",
      "Smaller, cleaner dialog panels",
      "45 cities with full port data",
      "Shipyard: buy ships, repair hull",
      "Tavern: recruit crew, buy drinks, hear rumors",
      "Governor: ranks, letters of marque",
      "Era selection (6 historical eras)",
      "Save/load system (5 slots)",
      "Event log and calendar",
      "Asset pack switching (classic / AI sprites)",
      "Zoom level setting (far / normal / close)",
      "Polish language support",
    ],
  },
  {
    version: "0.8.0",
    date: "2026-02-18",
    changes: [
      "Initial release: Caribbean sailing, trading, combat",
      "Procedural world generation with factions",
      "Sea battle system",
      "Port trading and docking",
    ],
  },
];
